/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.extensions.jakartaee.web.mansart.pool.dev;

import io.vidocq.mansart.pool.core.MansartDataSource;
import io.vidocq.runtime.extensions.jakartaee.web.mansart.pool.MansartPoolExtension;
import io.vidocq.runtime.extensions.jakartaee.web.mansart.pool.live.MansartPoolsLive;
import io.vidocq.runtime.spi.VidocqConfiguration;
import io.vidocq.vauban.core.container.VaubanContainerBuilder;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * The Mansart pool extension booted on in-memory H2 databases, as Vidocq boots it before the container starts: its
 * pools open and published to {@link MansartPoolsLive}. H2 is told to store unquoted names in lower case, as
 * PostgreSQL does. {@link #close} stops the extension, which clears the holder.
 */
final class TestPools implements AutoCloseable {

    /** The tables of the SQL spec's tests: tasks referring to projects, a view, and a table of another schema. */
    static final String[] SCHEMA = {
        "CREATE TABLE projects (id BIGINT PRIMARY KEY, name VARCHAR(80) NOT NULL)",
        "CREATE TABLE tasks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(200) NOT NULL, "
                + "price NUMERIC(10,2), due DATE, done BOOLEAN DEFAULT FALSE NOT NULL, "
                + "project_id BIGINT REFERENCES projects (id))",
        "CREATE INDEX idx_tasks_title ON tasks (title)",
        "CREATE VIEW open_tasks AS SELECT id, title FROM tasks WHERE NOT done",
        "CREATE SCHEMA sales",
        "CREATE TABLE sales.orders (id INT PRIMARY KEY, \"Total\" NUMERIC(38,0))",
        "INSERT INTO projects VALUES (1, 'vidocq'), (2, 'mansart')",
        "INSERT INTO tasks (title, price, due, project_id) VALUES ('first', 12.50, DATE '2026-10-01', 1), "
                + "('second', NULL, NULL, 2), ('third', 3, DATE '2026-10-03', 1)"};

    private final MansartPoolExtension extension = new MansartPoolExtension();

    private TestPools() {}

    /** An in-memory H2 database of its own, kept while the JVM runs, its unquoted names in lower case. */
    static String h2(String name) {
        return "jdbc:h2:mem:sql-" + name + "-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";
    }

    /** Configures the extension with these keys and values and opens its pools. */
    static TestPools boot(String... keysAndValues) {
        Map<String, String> data = new HashMap<>();
        for (int i = 0; i < keysAndValues.length; i += 2) {
            data.put(keysAndValues[i], keysAndValues[i + 1]);
        }
        TestPools pools = new TestPools();
        pools.extension.configure(new VidocqConfiguration() {
            @Override
            public Optional<String> property(String key) {
                return Optional.ofNullable(data.get(key));
            }

            @Override
            public Iterable<String> propertyNames() {
                return data.keySet();
            }
        });
        pools.extension.beforeStart(new VaubanContainerBuilder());
        return pools;
    }

    /** One {@code @Default} pool of the SQL spec's tables. */
    static TestPools withTables() {
        TestPools pools = boot("vidocq.pool.url", h2("default"), "vidocq.pool.maxSize", "4");
        pools.run("@Default", SCHEMA);
        return pools;
    }

    /** The open pool labelled {@code label}, read from the holder the panel reads. */
    MansartDataSource pool(String label) {
        return MansartPoolsLive.pools().stream().filter(p -> p.label().equals(label)).findFirst().orElseThrow()
                .pool();
    }

    /** Runs {@code statements} on pool {@code label}, committed. */
    void run(String label, String... statements) {
        try (Connection connection = pool(label).getConnection(); Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                statement.execute(sql);
            }
        } catch (SQLException failed) {
            throw new IllegalStateException(failed);
        }
    }

    @Override
    public void close() {
        extension.onStop();
    }
}
