/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.maven.idea;

import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Guards the bytes of a generated IntelliJ IDEA shared run configuration.
 *
 * <p>The reference is the hand-written {@code .run/McpTimeServerApp.run.xml} of the
 * {@code lc4jcdi-on-vidocq} example (commit {@code 35da0ef}): run from IntelliJ IDEA 2026.2
 * (IU-262.10968.63) after {@code mvn clean}, it ran Make then {@code vidocq:generate}, and the application
 * started with a complete bean index. The renderer must reproduce it byte for byte, in the format
 * IntelliJ itself writes (2-space indent, {@code " />"}, LF, no XML declaration, nothing after the root
 * element), so that IntelliJ's own re-serialisation equals the generated body and it never rewrites the
 * file for formatting alone.
 */
class RunConfigurationRendererTest {

    /** {@code lc4jcdi-on-vidocq/.run/McpTimeServerApp.run.xml} at commit 35da0ef, 653 bytes. */
    static final String MEASURED_REFERENCE = """
            <component name="ProjectRunConfigurationManager">
              <configuration default="false" name="McpTimeServerApp" type="Application" factoryName="Application">
                <option name="ALTERNATIVE_JRE_PATH" value="temurin-25" />
                <option name="ALTERNATIVE_JRE_PATH_ENABLED" value="true" />
                <option name="MAIN_CLASS_NAME" value="io.vidocq.tools.lc4jcdi.mcptimeserver.McpTimeServerApp" />
                <module name="mcp-time-server" />
                <method v="2">
                  <option name="Make" enabled="true" />
                  <option name="Maven.BeforeRunTask" enabled="true" file="$PROJECT_DIR$/mcp-time-server/pom.xml" goal="vidocq:generate" />
                </method>
              </configuration>
            </component>""";

    static final IdeaApplication MCP_TIME_SERVER = new IdeaApplication(
            "io.vidocq.tools:mcp-time-server",
            "io.vidocq.tools.lc4jcdi.mcptimeserver.McpTimeServerApp",
            "McpTimeServerApp",
            "mcp-time-server",
            "mcp-time-server/pom.xml",
            "vidocq:generate");

    @Test
    void body_withThePinnedJre_isTheMeasuredReferenceByteForByte() {
        String body = RunConfigurationRenderer.body(MCP_TIME_SERVER, "temurin-25", true);

        assertEquals(MEASURED_REFERENCE, body);
        assertEquals(653, body.getBytes(StandardCharsets.UTF_8).length);
    }

    @Test
    void body_byDefault_leavesTheJdkToIntelliJ() {
        String body = RunConfigurationRenderer.body(MCP_TIME_SERVER, null, true);

        assertFalse(body.contains("ALTERNATIVE_JRE_PATH"), body);
        assertEquals(MEASURED_REFERENCE
                        .replace("    <option name=\"ALTERNATIVE_JRE_PATH\" value=\"temurin-25\" />\n", "")
                        .replace("    <option name=\"ALTERNATIVE_JRE_PATH_ENABLED\" value=\"true\" />\n", ""),
                body);
        assertEquals("fd283510b3a7f167725776580c2dc4dffdcd429bd974ddf3e47ec3f7f26de6f8",
                RunConfigurationRenderer.sha256(body));
    }

    @Test
    void file_startsWithTheMarkerLineThatCarriesTheBodyHash() {
        String file = RunConfigurationRenderer.file(MCP_TIME_SERVER, null, true);

        assertEquals("<!-- Generated by vidocq:idea. Run \"mvn vidocq:idea\" to update it; once edited, it is left"
                        + " alone. sha256:fd283510b3a7f167725776580c2dc4dffdcd429bd974ddf3e47ec3f7f26de6f8 -->\n"
                        + RunConfigurationRenderer.body(MCP_TIME_SERVER, null, true),
                file);
    }

    @Test
    void markerComment_neverContainsADoubleHyphen() {
        String marker = RunConfigurationRenderer.markerLine(RunConfigurationRenderer.body(MCP_TIME_SERVER, null, true));
        String commentText = marker.substring("<!--".length(), marker.length() - "-->".length());

        assertFalse(commentText.contains("--"), "'--' is not allowed inside an XML comment: " + marker);
    }

    @Test
    void body_withoutTheBeforeLaunchStep_keepsOnlyMake() {
        String body = RunConfigurationRenderer.body(MCP_TIME_SERVER, null, false);

        assertTrue(body.contains("""
                    <method v="2">
                      <option name="Make" enabled="true" />
                    </method>
                """), body);
        assertFalse(body.contains("Maven.BeforeRunTask"), body);
    }

    @Test
    void body_runsTheExecutionThatCarriesTheGenerateConfiguration() {
        IdeaApplication application = new IdeaApplication("com.example:beta", "com.example.beta.BetaApp",
                "BetaApp", "beta", "apps/beta/pom.xml", "vidocq:generate@generate");

        String body = RunConfigurationRenderer.body(application, null, true);

        assertTrue(body.contains("<option name=\"Maven.BeforeRunTask\" enabled=\"true\""
                + " file=\"$PROJECT_DIR$/apps/beta/pom.xml\" goal=\"vidocq:generate@generate\" />"), body);
    }

    /**
     * IntelliJ's gutter reuses a configuration only when {@code MAIN_CLASS_NAME} equals the class's
     * qualified name, which uses dots for a nested class ({@code AbstractApplicationConfigurationProducer}),
     * while Maven properties carry the binary name with {@code $}.
     */
    @Test
    void body_writesANestedMainClassWithDots() {
        IdeaApplication application = new IdeaApplication("com.example:app", "com.example.Outer$Main",
                "Main", "app", "pom.xml", "vidocq:generate");

        String body = RunConfigurationRenderer.body(application, null, true);

        assertTrue(body.contains("<option name=\"MAIN_CLASS_NAME\" value=\"com.example.Outer.Main\" />"), body);
    }

    @Test
    void attributes_areEscapedAsIntelliJEscapesThem() {
        assertEquals("A &amp; &lt;B&gt; &quot;C&quot; it's&#10;x&#13;y&#9;z",
                RunConfigurationRenderer.escapeAttribute("A & <B> \"C\" it's\nx\ry\tz"));

        IdeaApplication application = new IdeaApplication("com.example:app", "com.example.App",
                "A & <B>", "m\"odule", "pom.xml", "vidocq:generate");
        String body = RunConfigurationRenderer.body(application, "my \"jdk\"", true);

        assertTrue(body.contains("name=\"A &amp; &lt;B&gt;\""), body);
        assertTrue(body.contains("<module name=\"m&quot;odule\" />"), body);
        assertTrue(body.contains("value=\"my &quot;jdk&quot;\""), body);
    }

    @Test
    void format_isTheOneIntelliJWrites() {
        String file = RunConfigurationRenderer.file(MCP_TIME_SERVER, "temurin-25", true);

        assertFalse(file.contains("\r"), "LF only");
        assertFalse(file.contains("<?xml"), "no XML declaration");
        assertFalse(file.endsWith("\n"), "nothing after the root element");
        assertTrue(file.split("\n")[1].startsWith("<component"), "the body follows the marker line");
    }

    @Test
    void fileName_followsIntelliJsSanitisation() {
        assertEquals("McpTimeServerApp.run.xml", RunConfigurationRenderer.fileName("McpTimeServerApp"));
        assertEquals("Beta_ server_api.run.xml", RunConfigurationRenderer.fileName("Beta: server/api"));
        assertEquals("a_b_c_d_e_f_g_h_i_j.run.xml", RunConfigurationRenderer.fileName("a/b\\c?d<e>f*g|h\"i\tj"));
        assertEquals("x".repeat(255) + ".run.xml", RunConfigurationRenderer.fileName("x".repeat(300)));
    }
}
