/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.maven.idea;

import io.vidocq.runtime.maven.idea.RunConfigurationFiles.State;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.util.EnumSet;
import java.util.Set;

import static io.vidocq.runtime.maven.idea.RunConfigurationRendererTest.MCP_TIME_SERVER;
import static io.vidocq.runtime.maven.idea.RunConfigurationRendererTest.MEASURED_REFERENCE;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Guards who owns a file in {@code .run/}.
 *
 * <p>{@code vidocq:idea} owns a file only while it carries a valid marker, whose hash is the one of the
 * body it wrote. IntelliJ drops comments when it saves a configuration after an edit, so an edited file
 * loses its marker and becomes the user's: the goal leaves it alone and only warns, in write mode and in
 * check mode alike. A file with the expected body but no marker (the hand-written reference, once
 * {@code vidocq.idea.jre} matches it) is adopted by adding the marker.
 */
class RunConfigurationFilesTest {

    static final String BODY = RunConfigurationRenderer.body(MCP_TIME_SERVER, null, true);

    @Test
    void anAbsentFileIsMissing() {
        assertEquals(State.MISSING, RunConfigurationFiles.classify(null, BODY));
    }

    @Test
    void aGeneratedFileWithTheExpectedBodyIsUnchanged() {
        assertEquals(State.UNCHANGED, RunConfigurationFiles.classify(bytes(file(BODY)), BODY));
    }

    @Test
    void lineEndingsAndATrailingNewlineAreNotEdits() {
        String checkedOutWithCrLf = file(BODY).replace("\n", "\r\n") + "\r\n\n";

        assertEquals(State.UNCHANGED, RunConfigurationFiles.classify(bytes(checkedOutWithCrLf), BODY));
    }

    @Test
    void anOlderMarkerWordingWithTheSameBodyIsUnchanged() {
        String older = "<!-- Generated by vidocq:idea from an older plugin sha256:"
                + RunConfigurationRenderer.sha256(BODY) + " -->\n" + BODY;

        assertEquals(State.UNCHANGED, RunConfigurationFiles.classify(bytes(older), BODY));
    }

    @Test
    void aGeneratedFileWithAnotherBodyIsOutdated() {
        String stale = RunConfigurationRenderer.file(new IdeaApplication("io.vidocq.tools:mcp-time-server",
                "io.vidocq.tools.lc4jcdi.mcptimeserver.OldApp", "McpTimeServerApp", "mcp-time-server",
                "mcp-time-server/pom.xml", "vidocq:generate"), null, true);

        assertEquals(State.OUTDATED, RunConfigurationFiles.classify(bytes(stale), BODY));
    }

    @Test
    void anUnmarkedFileWithTheExpectedBodyIsAdopted() {
        String pinned = RunConfigurationRenderer.body(MCP_TIME_SERVER, "temurin-25", true);

        assertEquals(State.UNMARKED, RunConfigurationFiles.classify(bytes(MEASURED_REFERENCE), pinned));
    }

    @Test
    void aMarkedFileWhoseHashNoLongerMatchesWasEdited() {
        String edited = file(BODY).replace("<module name=\"mcp-time-server\" />",
                "<option name=\"VM_PARAMETERS\" value=\"-Xmx1g\" />\n    <module name=\"mcp-time-server\" />");

        assertEquals(State.EDITED, RunConfigurationFiles.classify(bytes(edited), BODY));
    }

    @Test
    void anUnmarkedFileWithAnotherBodyBelongsToTheUser() {
        assertEquals(State.FOREIGN, RunConfigurationFiles.classify(bytes(MEASURED_REFERENCE), BODY));
    }

    @Test
    void anUndecodableFileBelongsToTheUser() {
        assertEquals(State.FOREIGN, RunConfigurationFiles.classify(new byte[] {(byte) 0xC3, (byte) 0x28}, BODY));
    }

    /** Check mode fails exactly where a write would change a file. */
    @Test
    void onlyStatesThatWriteFailTheCheck() {
        Set<State> writing = EnumSet.of(State.MISSING, State.OUTDATED, State.UNMARKED);
        for (State state : State.values()) {
            assertEquals(writing.contains(state), state.writes(), state.name());
        }
        assertTrue(State.EDITED.userOwned());
        assertTrue(State.FOREIGN.userOwned());
        assertFalse(State.UNMARKED.userOwned());
    }

    @Test
    void theMarkerIsRecognisedWhetherOrNotItsHashStillMatches() {
        assertTrue(RunConfigurationFiles.isGenerated(bytes(file(BODY))));
        assertTrue(RunConfigurationFiles.isGenerated(bytes(file(BODY).replace("McpTimeServerApp\"", "Other\""))));
        assertFalse(RunConfigurationFiles.isGenerated(bytes(MEASURED_REFERENCE)));
        assertFalse(RunConfigurationFiles.isGenerated(new byte[0]));
    }

    @Test
    void theShownBodyDropsTheMarkerAndNormalisesLineEndings() {
        assertEquals(BODY, RunConfigurationFiles.shownBody(bytes(file(BODY).replace("\n", "\r\n") + "\r\n")));
        assertEquals(MEASURED_REFERENCE, RunConfigurationFiles.shownBody(bytes(MEASURED_REFERENCE)));
    }

    /** The JDK a file pins, as IntelliJ stores it: an enabled alternative JRE, with its attribute escaping undone. */
    @Test
    void thePinnedJdkOfAFileIsRead() {
        assertEquals("temurin-25", RunConfigurationFiles.pinnedJre(bytes(MEASURED_REFERENCE)));
        assertEquals("temurin-25", RunConfigurationFiles.pinnedJre(bytes(file(
                RunConfigurationRenderer.body(MCP_TIME_SERVER, "temurin-25", true)))));
        assertEquals("a \"b\" & <c>", RunConfigurationFiles.pinnedJre(bytes(
                RunConfigurationRenderer.body(MCP_TIME_SERVER, "a \"b\" & <c>", true))));
        assertNull(RunConfigurationFiles.pinnedJre(bytes(BODY)));
        assertNull(RunConfigurationFiles.pinnedJre(bytes(MEASURED_REFERENCE.replace(
                "ALTERNATIVE_JRE_PATH_ENABLED\" value=\"true\"", "ALTERNATIVE_JRE_PATH_ENABLED\" value=\"false\""))));
        assertNull(RunConfigurationFiles.pinnedJre(bytes(MEASURED_REFERENCE.replace("value=\"temurin-25\"", "value=\"\""))));
    }

    private static String file(String body) {
        return RunConfigurationRenderer.markerLine(body) + "\n" + body;
    }

    private static byte[] bytes(String text) {
        return text.getBytes(StandardCharsets.UTF_8);
    }
}
