<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.vidocq.runtime</groupId>
        <artifactId>vidocq-runtime-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>vidocq-runtime-examples</artifactId>
    <packaging>pom</packaging>
    <name>Vidocq :: Examples</name>
    <description>Example applications for Vidocq</description>

    <modules>
        <module>vidocq-runtime-external-rest-lib</module>
        <module>vidocq-runtime-cassini-rest-example</module>
        <module>vidocq-runtime-mansart-h2-example</module>
    </modules>

    <build>
        <plugins>
            <!-- Inherits the checkpom execution from vidocq-runtime-parent/pluginManagement. -->
            <plugin>
                <groupId>io.vidocq.runtime</groupId>
                <artifactId>vidocq-runtime-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
