module io.vidocq.runtime.examples.rest {
    requires java.logging;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.ws.rs;
    requires jakarta.json.bind;

    requires io.vidocq.runtime.core;
    requires io.vidocq.runtime.spi;
    requires io.vidocq.runtime.ext.rest.cassini;
    // Required by cassini-processor APT output: $$CassiniAdapter implements
    // io.vidocq.cassini.spi.gen.ResourceAdapter and uses InjectionSupport/ParamKind.
    requires io.vidocq.cassini.api;
    requires io.vidocq.chappe.api;
    requires io.vidocq.vauban.core;

    // ZERO opens. The APT generates TodoResource$$CassiniAdapter/$$CassiniRoutes; cassini obtains them
    // via ServiceLoader (provides below) and dispatches/injects through the in-package adapter — no
    // reflective setAccessible. The package stays EXPORTED (not opened) only because the co-located
    // `Todo` record is read by Champollion JSON-B via publicLookup (an export suffices, no opens) —
    // same accepted exception as the `model` package in cassini-examples. (Splitting `Todo` into a
    // dedicated model subpackage would let this package be fully closed — follow-up.)
    exports io.vidocq.runtime.examples.rest;
    provides io.vidocq.cassini.spi.gen.ResourceAdapter
            with io.vidocq.runtime.examples.rest.TodoResource$$CassiniAdapter;
    provides io.vidocq.cassini.spi.gen.RouteProvider
            with io.vidocq.runtime.examples.rest.TodoResource$$CassiniRoutes;

    // Generated by Vauban APT: lets the container instantiate this module's beans in-module
    // (new X(...)) via ServiceLoader on the strict module path, instead of reflecting into them.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.runtime.examples.rest._VaubanComponents;

    // java.util.logging.LogManager instantiates StdoutHandler by reflection via
    // Class.newInstance() when loading logging.properties — requires that
    // the package is exported to java.logging.
    exports io.vidocq.runtime.logging to java.logging;
}
