package io.vidocq.runtime.examples.mansart;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.context.Initialized;
import jakarta.enterprise.event.Observes;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Demo-only bootstrap schema. The {@code @Observes @Initialized(ApplicationScoped.class)}
 * trigger fires when the Vauban CDI container is fully started, after the {@link DataSource}
 * bean published by the mansart-pool extension is available. {@code @ApplicationScoped} beans
 * are otherwise lazy in Vauban — without the observer, this bean would never be instantiated.
 *
 * <p>In a real application you would use Flyway / Liquibase or your DB migration tool of
 * choice — this is intentionally minimal so the example stays runnable without extra deps.
 */
@ApplicationScoped
public class SchemaInitializer {

    // Indirect via Instance<> so the Vauban APT does not statically reject the @Inject: the
    // DataSource bean is contributed by mansart-pool-extension at runtime and not visible to the
    // compile-time index of this module.
    @Inject
    Instance<DataSource> dataSourceInstance;

    void onStart(@Observes @Initialized(ApplicationScoped.class) Object event) {
        initSchema();
    }

    void initSchema() {
        DataSource dataSource = dataSourceInstance.get();
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"products\"");
            s.execute("CREATE TABLE \"products\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL,"
                    + "  \"price\" DOUBLE NOT NULL"
                    + ")");
            s.execute("INSERT INTO \"products\"(\"name\", \"price\") VALUES "
                    + "('Espresso', 2.50), ('Cappuccino', 3.50), ('Latte', 4.00)");
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to initialize H2 demo schema", e);
        }
    }
}
