/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.examples.mansart;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.context.Initialized;
import jakarta.enterprise.event.Observes;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;
import jakarta.inject.Named;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Demo-only bootstrap schema. The {@code @Observes @Initialized(ApplicationScoped.class)}
 * trigger fires when the Vauban CDI container is fully started, after the {@link DataSource}
 * bean published by the mansart-pool extension is available. {@code @ApplicationScoped} beans
 * are otherwise lazy in Vauban — without the observer, this bean would never be instantiated.
 *
 * <p>In a real application you would use Flyway / Liquibase or your DB migration tool of
 * choice — this is intentionally minimal so the example stays runnable without extra deps.
 */
@ApplicationScoped
public class SchemaInitializer {

    // Indirect via Instance<> so the Vauban APT does not statically reject the @Inject: the @Default
    // DataSource bean is contributed by mansart-pool-extension at runtime and not visible to the
    // compile-time index of this module.
    @Inject
    Instance<DataSource> dataSourceInstance;

    // The "audit" datasource, by contrast, IS visible at compile time: its @Named("audit") holder is
    // generated into this module by mansart-pool-datasources-codegen, so it can be injected directly.
    @Inject
    @Named("audit")
    DataSource auditDataSource;

    void onStart(@Observes @Initialized(ApplicationScoped.class) Object event) {
        initSchema();
    }

    void initSchema() {
        DataSource dataSource = dataSourceInstance.get();
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"products\"");
            s.execute("CREATE TABLE \"products\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL,"
                    + "  \"price\" DOUBLE NOT NULL"
                    + ")");
            s.execute("INSERT INTO \"products\"(\"name\", \"price\") VALUES "
                    + "('Espresso', 2.50), ('Cappuccino', 3.50), ('Latte', 4.00)");
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to initialize H2 demo schema", e);
        }

        // The "audit" table lives in a DISTINCT H2 database, reached through the @Named("audit")
        // DataSource above — proof that the named datasource is wired and independent of @Default.
        try (Connection c = auditDataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"audit_log\"");
            s.execute("CREATE TABLE \"audit_log\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"action\" VARCHAR(500) NOT NULL"
                    + ")");
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to initialize H2 audit schema", e);
        }
    }
}
