<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <parent>
        <groupId>io.vidocq.mpserver</groupId>
        <artifactId>vidocq-parent</artifactId>
    </parent>

    <artifactId>vidocq-core</artifactId>
    <name>Vidocq :: Core</name>
    <description>Vidocq server engine and bootstrap</description>

    <dependencies>
        <dependency>
            <groupId>io.vidocq.mpserver</groupId>
            <artifactId>vidocq-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.vauban</groupId>
            <artifactId>vauban-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.vauban</groupId>
            <artifactId>vauban-classloader-spi</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
