module io.vidocq.runtime.examples.jwt {
    requires java.logging;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.ws.rs;
    requires jakarta.annotation;            // @RolesAllowed / @PermitAll
    requires jakarta.json.bind;

    requires io.vidocq.runtime.core;
    requires io.vidocq.runtime.spi;
    requires io.vidocq.runtime.ext.rest.cassini;
    // Pulls all of cervantes transitively (api/core/cdi-vauban/jaxrs + ravel) and registers the
    // JWT BuildCompatibleExtension.
    requires io.vidocq.runtime.ext.cervantes.jwt;
    requires org.eclipse.microprofile.jwt;  // JsonWebToken injected in the resource

    requires io.vidocq.cassini.api;
    requires io.vidocq.chappe.api;
    requires io.vidocq.vauban.core;

    // JAX-RS reflects on the resource and injects the @RequestScoped JsonWebToken field.
    opens io.vidocq.runtime.examples.jwt;

    // Generated by Vauban APT: in-module instantiation of this module's beans on the module path.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.runtime.examples.jwt._VaubanComponents;

    exports io.vidocq.runtime.logging to java.logging;
}
