module io.vidocq.runtime.examples.jwt {
    requires java.logging;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.ws.rs;
    requires jakarta.annotation;            // @RolesAllowed / @PermitAll
    requires jakarta.json.bind;

    requires io.vidocq.runtime.core;
    requires io.vidocq.runtime.spi;
    requires io.vidocq.runtime.ext.rest.cassini;
    // Pulls all of cervantes transitively (api/core/cdi-vauban/jaxrs + ravel) and registers the
    // JWT BuildCompatibleExtension.
    requires io.vidocq.runtime.ext.cervantes.jwt;
    requires org.eclipse.microprofile.jwt;  // JsonWebToken injected in the resource

    requires io.vidocq.cassini.api;
    requires io.vidocq.chappe.api;
    requires io.vidocq.vauban.core;

    // ZERO opens AND zero exports on the resource package. The APT (cassini-rest-extension-codegen)
    // generates SecuredResource$$CassiniAdapter/$$CassiniRoutes; cassini obtains them via ServiceLoader
    // from the closed package (dispatch + @Context SecurityContext method-param resolution run in the
    // adapter — SecuredResource has no injected fields). Vauban creates the @RequestScoped resource's
    // proxy in-module via _VaubanComponents. No reflection into this package.
    provides io.vidocq.cassini.spi.gen.ResourceAdapter
            with io.vidocq.runtime.examples.jwt.SecuredResource$$CassiniAdapter;
    provides io.vidocq.cassini.spi.gen.RouteProvider
            with io.vidocq.runtime.examples.jwt.SecuredResource$$CassiniRoutes;

    // Generated by Vauban APT: in-module instantiation of this module's beans on the module path.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.runtime.examples.jwt._VaubanComponents;

    exports io.vidocq.runtime.logging to java.logging;
}
