/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
module io.vidocq.runtime.examples.jwt {
    requires java.logging;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.ws.rs;
    requires jakarta.annotation;            // @RolesAllowed / @PermitAll
    requires jakarta.json.bind;

    requires io.vidocq.runtime.core;
    requires io.vidocq.runtime.spi;
    requires io.vidocq.runtime.ext.rest.cassini;
    // Pulls all of cervantes transitively (api/core/cdi-vauban/jaxrs + ravel) and registers the
    // JWT BuildCompatibleExtension.
    requires io.vidocq.runtime.ext.cervantes.jwt;
    requires org.eclipse.microprofile.jwt;  // JsonWebToken injected in the resource

    requires io.vidocq.cassini.api;
    requires io.vidocq.chappe.api;
    requires io.vidocq.vauban.core;

    // ZERO opens AND zero exports on the resource package. The APT (cassini-rest-extension-codegen)
    // generates SecuredResource$$CassiniAdapter/$$CassiniRoutes; cassini obtains them via ServiceLoader
    // from the closed package (dispatch + @Context SecurityContext method-param resolution run in the
    // adapter — SecuredResource has no injected fields). Vauban creates the @RequestScoped resource's
    // proxy in-module via _VaubanComponents. No reflection into this package.
    provides io.vidocq.cassini.spi.gen.ResourceAdapter
            with io.vidocq.runtime.examples.jwt.SecuredResource$$CassiniAdapter;
    provides io.vidocq.cassini.spi.gen.RouteProvider
            with io.vidocq.runtime.examples.jwt.SecuredResource$$CassiniRoutes;

    // Generated by Vauban APT: in-module instantiation of this module's beans on the module path.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.runtime.examples.jwt._VaubanComponents;

    exports io.vidocq.runtime.logging to java.logging;
}
