<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <parent>
        <groupId>io.vidocq.mpserver</groupId>
        <artifactId>vidocq-mps-core-extensions</artifactId>
    </parent>

    <artifactId>vidocq-mps-servlet-chappe-extension</artifactId>
    <name>Vidocq :: Core Extensions :: Servlet (Chappe)</name>
    <description>Implémentation Jakarta Servlet 6.1 sur le moteur HTTP Chappe</description>

    <dependencies>
        <dependency>
            <groupId>io.vidocq.mpserver</groupId>
            <artifactId>vidocq-mps-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mpserver</groupId>
            <artifactId>vidocq-mps-chappe-extension</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.vauban</groupId>
            <artifactId>vauban-core</artifactId>
        </dependency>
        <dependency>
            <groupId>fr.vidocq.chappe</groupId>
            <artifactId>chappe-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
        </dependency>

        <dependency>
            <groupId>fr.vidocq.chappe</groupId>
            <artifactId>chappe-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
