/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.examples.petstore;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.context.Initialized;
import jakarta.enterprise.event.Observes;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Demo-only bootstrap schema. The {@code @Observes @Initialized(ApplicationScoped.class)} trigger
 * fires when the Vauban CDI container is fully started, after the {@link DataSource} bean published
 * by the mansart-pool extension is available.
 *
 * <p>In a real application you would use a migration tool (Flyway / Liquibase). This is intentionally
 * minimal so the example stays runnable without extra deps. The four flat tables mirror the entities;
 * relations are joined in {@code PetService}, not by the database.
 */
@ApplicationScoped
public class SchemaInitializer {

    // Indirect via Instance<> so the Vauban APT does not statically reject the @Inject: the
    // DataSource bean is contributed by mansart-pool-extension at runtime and not visible to the
    // compile-time index of this module.
    @Inject
    Instance<DataSource> dataSourceInstance;

    void onStart(@Observes @Initialized(ApplicationScoped.class) Object event) {
        initSchema();
    }

    void initSchema() {
        DataSource dataSource = dataSourceInstance.get();
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"pet_tags\"");
            s.execute("DROP TABLE IF EXISTS \"pets\"");
            s.execute("DROP TABLE IF EXISTS \"tags\"");
            s.execute("DROP TABLE IF EXISTS \"categories\"");

            s.execute("CREATE TABLE \"categories\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(120) NOT NULL UNIQUE"
                    + ")");
            s.execute("CREATE TABLE \"tags\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(120) NOT NULL UNIQUE"
                    + ")");
            s.execute("CREATE TABLE \"pets\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL,"
                    + "  \"category_id\" BIGINT,"
                    + "  \"status\" VARCHAR(20) NOT NULL,"
                    + "  \"price\" DOUBLE NOT NULL"
                    + ")");
            s.execute("CREATE TABLE \"pet_tags\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"pet_id\" BIGINT NOT NULL,"
                    + "  \"tag_id\" BIGINT NOT NULL"
                    + ")");

            // Seed: 2 categories, 3 tags, 3 pets, a few links.
            s.execute("INSERT INTO \"categories\"(\"id\", \"name\") VALUES (1, 'Dog'), (2, 'Cat')");
            s.execute("INSERT INTO \"tags\"(\"id\", \"name\") VALUES "
                    + "(1, 'friendly'), (2, 'trained'), (3, 'playful')");
            s.execute("INSERT INTO \"pets\"(\"id\", \"name\", \"category_id\", \"status\", \"price\") VALUES "
                    + "(1, 'Rex',     1, 'available', 120.00),"
                    + "(2, 'Whiskers',2, 'pending',    80.00),"
                    + "(3, 'Buddy',   1, 'sold',      150.00)");
            s.execute("INSERT INTO \"pet_tags\"(\"pet_id\", \"tag_id\") VALUES "
                    + "(1, 1), (1, 2), (2, 3), (3, 1)");

            // The seed inserts explicit ids, but GENERATED BY DEFAULT AS IDENTITY does not advance
            // the sequence on explicit inserts — restart each identity past the seeded max so the
            // next POST-generated id does not collide with an existing row.
            s.execute("ALTER TABLE \"categories\" ALTER COLUMN \"id\" RESTART WITH 3");
            s.execute("ALTER TABLE \"tags\" ALTER COLUMN \"id\" RESTART WITH 4");
            s.execute("ALTER TABLE \"pets\" ALTER COLUMN \"id\" RESTART WITH 4");
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to initialize H2 demo schema", e);
        }
    }
}
