--
-- Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
--
-- This program and the accompanying materials are made available under the
-- terms of the Eclipse Public License 2.0 which is available at
-- https://www.eclipse.org/legal/epl-2.0/
--
-- This Source Code may also be made available under the following Secondary
-- Licenses when the conditions for such availability set forth in the Eclipse
-- Public License, v. 2.0 are satisfied: GNU General Public License, version 2
-- or any later version, which is available at
-- https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
--
-- It is also made available under the European Union Public Licence v. 1.2,
-- which is available at
-- https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
--
-- SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
--

-- V1: Create the products table and seed three coffee items.
-- Managed by the vidocq-runtime-flyway-migration-extension on the @Default datasource.
CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(200) NOT NULL,
  "price" DOUBLE NOT NULL
);
INSERT INTO "products"("name", "price") VALUES ('Espresso', 2.50), ('Cappuccino', 3.50), ('Latte', 4.00);
