# Remplacer le ConsoleHandler par défaut par un handler sur stdout
handlers = io.vidocq.runtime.logging.StdoutHandler
.level = INFO

# Config du handler
io.vidocq.runtime.logging.StdoutHandler.level = ALL
io.vidocq.runtime.logging.StdoutHandler.formatter = io.vidocq.runtime.logging.CompactFormatter