package io.vidocq.runtime.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.spi.ToolProvider;
import java.util.stream.Stream;

/**
 * Packages an existing jlink runtime image into a native installer via
 * {@code jpackage}: {@code .dmg}/{@code .pkg} (macOS), {@code .deb}/{@code .rpm}
 * (Linux), {@code .exe}/{@code .msi} (Windows), or {@code app-image} (folder
 * cross-platform app without installing).
 *
 * <p>Reuses the image generated by the goal {@code vidocq:jlink} (by default
 * {@code target/dist/}) to avoid re-solving modules.</p>
 *
 * <h3>Default type</h3>
 * <p>{@code app-image}: produces an executable app folder without depending
 * native tools (no {@code dpkg}/{@code rpmbuild}/{@code pkgbuild}/
 * Wix). For a signed/distributable install, explicitly set
 * {@code &lt;type&gt;dmg|deb|rpm|msi|exe&lt;/type&gt;}.</p>
 */
@Mojo(name = "jpackage",
      defaultPhase = LifecyclePhase.PACKAGE,
      requiresDependencyResolution = ResolutionScope.RUNTIME)
public class VidocqJpackageMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Parameter(property = "vidocq.mainModule", required = true)
    private String mainModule;

    @Parameter(property = "vidocq.mainClass", required = true)
    private String mainClass;

    /** Application name (binary / installer). Default: {@code project.artifactId}. */
    @Parameter(defaultValue = "${project.artifactId}", property = "vidocq.appName")
    private String appName;

    /**
     * Application version. Default: {@code project.version} but without suffix
     * {@code -SNAPSHOT} (jpackage requires a digital version).
     */
    @Parameter(defaultValue = "${project.version}", property = "vidocq.appVersion")
    private String appVersion;

    /**
     * Typical package. Values: {@code app-image} (default), {@code dmg}, {@code pkg},
     * {@code deb}, {@code rpm}, {@code msi}, {@code exe}.
     */
    @Parameter(defaultValue = "app-image", property = "vidocq.jpackageType")
    private String type;

    /**
     * Input jlink runtime image. Default: {@code target/dist} (goal exit
     * {@code vidocq:jlink}).
     */
    @Parameter(defaultValue = "${project.build.directory}/dist", property = "vidocq.runtimeImage")
    private File runtimeImage;

    /** Output directory. Default: {@code target/installer}. */
    @Parameter(defaultValue = "${project.build.directory}/installer", property = "vidocq.installerDir")
    private File installerDir;

    /** Icon (optional). Format: {@code .icns} (macOS), {@code .ico} (Windows), {@code .png} (Linux). */
    @Parameter(property = "vidocq.icon")
    private File icon;

    /** Vendor (meta installer). */
    @Parameter(defaultValue = "${project.groupId}", property = "vidocq.vendor")
    private String vendor;

    /** Short description (meta install). Default: {@code project.description}. */
    @Parameter(defaultValue = "${project.description}", property = "vidocq.appDescription")
    private String description;

    @Override
    public void execute() throws MojoExecutionException {
        if (!runtimeImage.isDirectory()) {
            throw new MojoExecutionException(
                    "runtimeImage not found: " + runtimeImage
                            + ". Run the vidocq:jlink goal first (or point runtimeImage to an existing jlink image).");
        }

        String version = sanitizeVersion(appVersion);

        try {
            deleteRecursive(installerDir.toPath());
            Files.createDirectories(installerDir.toPath());

            List<String> args = new ArrayList<>();
            args.add("--type"); args.add(type);
            args.add("--name"); args.add(appName);
            args.add("--app-version"); args.add(version);
            args.add("--runtime-image"); args.add(runtimeImage.getAbsolutePath());
            args.add("--module"); args.add(mainModule + "/" + mainClass);
            args.add("--dest"); args.add(installerDir.getAbsolutePath());
            if (vendor != null && !vendor.isBlank())          { args.add("--vendor"); args.add(vendor); }
            if (description != null && !description.isBlank()) { args.add("--description"); args.add(description); }
            if (icon != null && icon.isFile())                { args.add("--icon"); args.add(icon.getAbsolutePath()); }

            getLog().info("Vidocq jpackage — type=" + type + " name=" + appName
                    + " version=" + version + " main=" + mainModule + "/" + mainClass);

            ToolProvider jpackage = ToolProvider.findFirst("jpackage")
                    .orElseThrow(() -> new MojoExecutionException(
                            "jpackage tool is not available in this JDK"));
            int rc = jpackage.run(System.out, System.err, args.toArray(new String[0]));
            if (rc != 0) {
                throw new MojoExecutionException("jpackage failed (rc=" + rc + ")");
            }
            getLog().info("Installer/app produced in: " + installerDir.getAbsolutePath());
        } catch (IOException e) {
            throw new MojoExecutionException("jpackage IO error", e);
        }
    }

    /** jpackage requires a version without qualifiers ({@code 1.2.3}). We strip {@code -SNAPSHOT} and others. */
    static String sanitizeVersion(String v) {
        if (v == null || v.isBlank()) return "0.0.0";
        String s = v.trim();
        int dash = s.indexOf('-');
        if (dash > 0) s = s.substring(0, dash);
        // Keep only numbers and points.
        StringBuilder out = new StringBuilder();
        for (char c : s.toCharArray()) {
            if (Character.isDigit(c) || c == '.') out.append(c);
        }
        String cleaned = out.toString();
        return cleaned.isBlank() ? "0.0.0" : cleaned;
    }

    static String osShortName() {
        String os = System.getProperty("os.name", "").toLowerCase(Locale.ROOT);
        if (os.contains("mac"))    return "macos";
        if (os.contains("win"))    return "windows";
        if (os.contains("linux"))  return "linux";
        return "unknown";
    }

    private static void deleteRecursive(Path root) throws IOException {
        if (!Files.exists(root)) return;
        try (Stream<Path> walk = Files.walk(root)) {
            walk.sorted(Comparator.reverseOrder()).forEach(p -> {
                try { Files.delete(p); } catch (IOException e) { throw new RuntimeException(e); }
            });
        }
    }
}
