package io.vidocq.runtime.maven;

import org.apache.maven.model.Dependency;
import org.apache.maven.model.Plugin;
import org.apache.maven.model.PluginExecution;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;
import org.codehaus.plexus.util.xml.Xpp3Dom;
import org.eclipse.aether.RepositorySystem;
import org.eclipse.aether.RepositorySystemSession;
import org.eclipse.aether.artifact.DefaultArtifact;
import org.eclipse.aether.repository.RemoteRepository;
import org.eclipse.aether.resolution.ArtifactRequest;
import org.eclipse.aether.resolution.ArtifactResolutionException;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Verifies that every {@code vidocq-runtime-<name>-extension} declared in the project
 * dependencies has its companion {@code vidocq-runtime-<name>-extension-codegen} bundle
 * in the {@code maven-compiler-plugin}'s {@code <annotationProcessorPaths>}, and vice versa.
 *
 * <p>Three checks are performed:</p>
 * <ol>
 *   <li><b>Missing codegen</b> — an extension is declared but its codegen bundle is absent
 *       from APT paths. The codegen artifact must actually exist in any reachable repository
 *       for this to flag (so extensions that legitimately ship no codegen, e.g. chappe, are
 *       silently ignored).</li>
 *   <li><b>Orphan codegen</b> — a codegen bundle is in APT paths but the matching extension
 *       is not in the dependency list. Usually a leftover after removing an extension.</li>
 *   <li><b>Version drift</b> — an extension and its codegen are declared with mismatching
 *       versions. Prevents the runtime adapter and the APT-generated bytecode from diverging
 *       across upgrades.</li>
 * </ol>
 *
 * <p>{@code vidocq-runtime-core-codegen} is treated as universal: it has no counterpart
 * runtime extension, so it never triggers an orphan or version-drift report.</p>
 *
 * <p>Default phase: {@code validate} — runs at the very start of every build so drift is
 * caught before any expensive work. Skipping with {@code -Dvidocq.checkpom.skip=true} or
 * downgrading failures to warnings with {@code -Dvidocq.checkpom.failOnMissing=false}.</p>
 */
@Mojo(name = "checkpom",
      defaultPhase = LifecyclePhase.VALIDATE,
      requiresDependencyResolution = ResolutionScope.NONE,
      threadSafe = true)
public class VidocqCheckPomMojo extends AbstractMojo {

    private static final String VIDOCQ_RUNTIME_GROUP = "io.vidocq.runtime";
    private static final String CORE_CODEGEN = "vidocq-runtime-core-codegen";
    private static final String MAVEN_COMPILER_KEY = "org.apache.maven.plugins:maven-compiler-plugin";
    /** Matches a runtime extension artifact, e.g. {@code vidocq-runtime-cassini-rest-extension}. */
    private static final Pattern EXTENSION_PATTERN =
            Pattern.compile("^vidocq-runtime-(.+)-extension$");
    /** Matches a codegen bundle artifact, e.g. {@code vidocq-runtime-cassini-rest-extension-codegen}. */
    private static final Pattern CODEGEN_PATTERN =
            Pattern.compile("^vidocq-runtime-(.+)-extension-codegen$");

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /** Skip the check entirely. */
    @Parameter(property = "vidocq.checkpom.skip", defaultValue = "false")
    private boolean skip;

    /**
     * If {@code true} (the default), a missing codegen / orphan codegen / version drift
     * makes the build fail. Set to {@code false} to downgrade to warnings.
     */
    @Parameter(property = "vidocq.checkpom.failOnMissing", defaultValue = "true")
    private boolean failOnMissing;

    @Parameter(defaultValue = "${repositorySystemSession}", readonly = true, required = true)
    private RepositorySystemSession repoSession;

    @Parameter(defaultValue = "${project.remoteProjectRepositories}", readonly = true)
    private List<RemoteRepository> remoteRepos;

    @Component
    private RepositorySystem repoSystem;

    @Override
    public void execute() throws MojoFailureException {
        if (skip) {
            getLog().info("Vidocq checkpom: skipped (-Dvidocq.checkpom.skip=true)");
            return;
        }

        // POM-only modules (reactor parents, codegen bundles) have no compile output
        // to protect — checking them produces noise without value.
        if ("pom".equals(project.getPackaging())) {
            getLog().debug("Vidocq checkpom: skipping POM-only module " + project.getArtifactId());
            return;
        }

        Map<String, String> extensions = collectExtensions();
        Map<String, String> codegenPaths = collectCodegenPaths();

        // A module that has no extension in its deps and no codegen bundle beyond the
        // core-codegen inherited from the parent has nothing actionable to verify.
        boolean hasOnlyCoreCodegen = codegenPaths.size() == 1 && codegenPaths.containsKey(CORE_CODEGEN);
        if (extensions.isEmpty() && (codegenPaths.isEmpty() || hasOnlyCoreCodegen)) {
            getLog().debug("Vidocq checkpom: " + project.getArtifactId()
                    + " has no Vidocq extension/codegen coupling, nothing to check");
            return;
        }

        List<String> issues = new ArrayList<>();
        issues.addAll(findMissingCodegens(extensions, codegenPaths));
        issues.addAll(findOrphanCodegens(extensions, codegenPaths));
        issues.addAll(findVersionDrifts(extensions, codegenPaths));

        if (issues.isEmpty()) {
            getLog().info("Vidocq checkpom: " + extensions.size() + " extension(s) and "
                    + codegenPaths.size() + " codegen path(s) — all aligned.");
            return;
        }

        for (String issue : issues) {
            if (failOnMissing) getLog().error(issue);
            else getLog().warn(issue);
        }
        if (failOnMissing) {
            throw new MojoFailureException("Vidocq checkpom found " + issues.size()
                    + " issue(s). Fix them or downgrade to warnings via -Dvidocq.checkpom.failOnMissing=false.");
        }
    }

    // ---- Check 1: Extension declared, codegen missing ----

    private List<String> findMissingCodegens(Map<String, String> extensions,
                                             Map<String, String> codegenPaths) {
        List<String> result = new ArrayList<>();
        for (Map.Entry<String, String> ext : extensions.entrySet()) {
            String extName = ext.getKey();
            String extVer = ext.getValue();
            Matcher m = EXTENSION_PATTERN.matcher(extName);
            if (!m.matches()) continue;
            String codegenName = "vidocq-runtime-" + m.group(1) + "-extension-codegen";
            if (codegenPaths.containsKey(codegenName)) continue;

            // Silent-skip if the extension has no published codegen artifact.
            if (!codegenArtifactExists(codegenName, extVer)) {
                getLog().debug("Vidocq checkpom: '" + extName + "' has no companion codegen artifact, skipping.");
                continue;
            }

            result.add("Vidocq extension '" + extName + "' is declared but its codegen bundle '"
                    + codegenName + "' is missing from maven-compiler-plugin/annotationProcessorPaths. "
                    + "Without it, the runtime falls back to reflection-based adapters.");
        }
        return result;
    }

    // ---- Check 2: Codegen path declared, no matching extension ----

    private List<String> findOrphanCodegens(Map<String, String> extensions,
                                            Map<String, String> codegenPaths) {
        List<String> result = new ArrayList<>();
        for (String codegenName : codegenPaths.keySet()) {
            if (CORE_CODEGEN.equals(codegenName)) continue;  // universal
            Matcher m = CODEGEN_PATTERN.matcher(codegenName);
            if (!m.matches()) continue;
            String extName = "vidocq-runtime-" + m.group(1) + "-extension";
            if (!extensions.containsKey(extName)) {
                result.add("Codegen bundle '" + codegenName + "' is in annotationProcessorPaths "
                        + "but its runtime extension '" + extName + "' is not declared as a "
                        + "dependency. Remove the orphan codegen path or add the extension.");
            }
        }
        return result;
    }

    // ---- Check 3: Extension and codegen at different versions ----

    private List<String> findVersionDrifts(Map<String, String> extensions,
                                           Map<String, String> codegenPaths) {
        List<String> result = new ArrayList<>();
        for (Map.Entry<String, String> codegen : codegenPaths.entrySet()) {
            String codegenName = codegen.getKey();
            String codegenVer = codegen.getValue();
            if (CORE_CODEGEN.equals(codegenName)) continue;
            Matcher m = CODEGEN_PATTERN.matcher(codegenName);
            if (!m.matches()) continue;
            String extName = "vidocq-runtime-" + m.group(1) + "-extension";
            String extVer = extensions.get(extName);
            if (extVer == null || codegenVer == null) continue;
            if (!Objects.equals(extVer, codegenVer)) {
                result.add("Version mismatch: '" + extName + "' is at " + extVer
                        + " but '" + codegenName + "' is at " + codegenVer
                        + ". Align both to the same version.");
            }
        }
        return result;
    }

    // ---- Extraction helpers ----

    private Map<String, String> collectExtensions() {
        Map<String, String> result = new LinkedHashMap<>();
        for (Dependency d : project.getDependencies()) {
            if (!VIDOCQ_RUNTIME_GROUP.equals(d.getGroupId())) continue;
            String aid = d.getArtifactId();
            // -codegen also contains "-extension-" — exclude explicitly.
            if (CODEGEN_PATTERN.matcher(aid).matches()) continue;
            if (!EXTENSION_PATTERN.matcher(aid).matches()) continue;
            result.put(aid, d.getVersion());
        }
        return result;
    }

    private Map<String, String> collectCodegenPaths() {
        Map<String, String> result = new LinkedHashMap<>();
        Plugin compiler = project.getPlugin(MAVEN_COMPILER_KEY);
        if (compiler == null) return result;

        // Configuration may live on the plugin itself or inside any <execution>.
        Stream<Object> configs = Stream.concat(
                Stream.ofNullable(compiler.getConfiguration()),
                compiler.getExecutions().stream().map(PluginExecution::getConfiguration)
        ).filter(Objects::nonNull);

        configs.forEach(cfg -> {
            if (!(cfg instanceof Xpp3Dom dom)) return;
            Xpp3Dom paths = dom.getChild("annotationProcessorPaths");
            if (paths == null) return;
            for (Xpp3Dom path : paths.getChildren("path")) {
                String gid = childText(path, "groupId");
                String aid = childText(path, "artifactId");
                String ver = childText(path, "version");
                if (VIDOCQ_RUNTIME_GROUP.equals(gid) && aid != null) {
                    result.putIfAbsent(aid, ver);
                }
            }
        });
        return result;
    }

    private static String childText(Xpp3Dom node, String name) {
        Xpp3Dom c = node.getChild(name);
        return c != null ? c.getValue() : null;
    }

    private boolean codegenArtifactExists(String artifactId, String version) {
        if (version == null) version = project.getVersion();
        try {
            ArtifactRequest req = new ArtifactRequest();
            req.setArtifact(new DefaultArtifact(VIDOCQ_RUNTIME_GROUP, artifactId, "pom", version));
            req.setRepositories(remoteRepos);
            repoSystem.resolveArtifact(repoSession, req);
            return true;
        } catch (ArtifactResolutionException ignored) {
            return false;
        }
    }
}
