/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.maven;

import io.vidocq.vauban.maven.generate.GenerationResult;
import io.vidocq.vauban.maven.generate.VaubanGenerator;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarFile;

/**
 * Generates the CDI bean index and pre-generates the proxies/interceptors
 * for dependencies not pre-processed by the VaubanProcessor APT.
 * <p>
 * For the project classes, the VaubanProcessor APT does everything during compilation.
 * This Mojo processes dependency JARs that have not been pre-processed
 * (no {@code META-INF/vauban-bce-processed}).
 * </p>
 * <p>
 * At runtime, the BCEs {@code @Enhancement} execute automatically
 * for beans without scope coming from non-pre-processed JARs
 * (via {@code BceProcessor.processEnhancementOnly()}).
 * </p>
 */
@Mojo(name = "generate",
      defaultPhase = LifecyclePhase.PROCESS_CLASSES,
      requiresDependencyResolution = ResolutionScope.COMPILE)
public class VidocqGenerateMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Parameter(defaultValue = "${project.build.outputDirectory}", readonly = true)
    private File outputDirectory;

    /**
     * List of dependencies to scan for proxy/index generation.
     * Format: {@code groupId:artifactId}. {@code artifactId} optional or
     * {@code *} to match any artifact of a groupId. Final Wildcard
     * accepted: {@code io.vidocq.*}, {@code com.acme.*:my-lib*}.
     * <p>The JARs bearing {@code META-INF/vauban-bce-processed} are
     * automatically excluded, whether they match or not.</p>
     */
    @Parameter
    private List<String> scanDependencies;

    @Override
    public void execute() throws MojoExecutionException {
        getLog().info("Vidocq - Generating bean index and proxies for dependencies");

        Path classesDir = outputDirectory.toPath();
        if (!Files.isDirectory(classesDir)) {
            getLog().info("No classes directory found, skipping");
            return;
        }

        try {
            List<Path> vidocqDeps = collectScannedDependencies();
            if (vidocqDeps.isEmpty()) {
                getLog().info("No dependencies to process (scanDependencies empty or all pre-processed)");
                return;
            }

            boolean aptProcessed = Files.exists(classesDir.resolve("META-INF/vauban-bce-processed"));
            if (aptProcessed) {
                getLog().info("APT already processed project classes (vauban-bce-processed found)");
            }

            URLClassLoader classLoader = buildClassLoader(classesDir);

            var config = new VaubanGenerator.Config(
                    vidocqDeps,
                    aptProcessed ? null : classesDir,
                    classesDir,
                    classLoader
            );

            // Save the existing beans.list (generated by APT)
            Path beansListPath = classesDir.resolve("META-INF/vauban-beans.list");
            List<String> existingBeans = new ArrayList<>();
            if (Files.exists(beansListPath)) {
                existingBeans = Files.readAllLines(beansListPath).stream()
                        .filter(l -> !l.isBlank() && !l.startsWith("#"))
                        .toList();
            }

            GenerationResult result;
            try {
                result = VaubanGenerator.generate(config);
            } finally {
                classLoader.close();
            }

            // Merge APT beans with dependency beans
            if (!existingBeans.isEmpty()) {
                var merged = new java.util.TreeSet<>(existingBeans);
                merged.addAll(result.discoveredBeanClasses());
                Files.createDirectories(beansListPath.getParent());
                var lines = new ArrayList<String>();
                lines.add("# Vauban discovered beans — APT + vidocq-runtime-maven-plugin");
                lines.addAll(merged);
                Files.write(beansListPath, lines);
                getLog().info("Bean index (merged): " + merged.size() + " class(es)");
            } else {
                getLog().info("Bean index: " + result.discoveredBeanClasses().size() + " class(es)");
            }

            for (String cls : result.discoveredBeanClasses()) {
                getLog().info("  - " + cls);
            }

            if (!result.generatedProxies().isEmpty()) {
                getLog().info("Proxies: " + result.generatedProxies().size() + " generated");
                for (String proxy : result.generatedProxies()) {
                    getLog().info("  - " + proxy);
                }
            }

            if (!result.generatedInterceptors().isEmpty()) {
                getLog().info("Interceptors: " + result.generatedInterceptors().size() + " generated");
                for (String interceptor : result.generatedInterceptors()) {
                    getLog().info("  - " + interceptor);
                }
            }

            for (String warning : result.warnings()) {
                getLog().warn(warning);
            }

        } catch (IOException e) {
            throw new MojoExecutionException("Failed to generate bean index", e);
        }
    }

    private URLClassLoader buildClassLoader(Path classesDir) throws MalformedURLException {
        List<URL> urls = new ArrayList<>();
        urls.add(classesDir.toUri().toURL());
        for (var artifact : project.getArtifacts()) {
            if (artifact.getFile() != null) {
                urls.add(artifact.getFile().toURI().toURL());
            }
        }
        return new URLClassLoader(urls.toArray(new URL[0]), getClass().getClassLoader());
    }

    private List<Path> collectScannedDependencies() throws IOException {
        if (scanDependencies == null || scanDependencies.isEmpty()) {
            return List.of();
        }
        List<Pattern> patterns = scanDependencies.stream().map(Pattern::parse).toList();
        List<Path> deps = new ArrayList<>();
        for (var artifact : project.getArtifacts()) {
            if (artifact.getFile() == null) continue;
            String g = artifact.getGroupId();
            String a = artifact.getArtifactId();
            if (patterns.stream().noneMatch(p -> p.matches(g, a))) continue;
            Path jar = artifact.getFile().toPath();
            if (isAlreadyProcessed(jar)) {
                getLog().debug("Skipping " + g + ":" + a + " (vauban-bce-processed)");
                continue;
            }
            deps.add(jar);
        }
        return deps;
    }

    private static boolean isAlreadyProcessed(Path jar) throws IOException {
        if (Files.isDirectory(jar)) {
            return Files.exists(jar.resolve("META-INF/vauban-bce-processed"));
        }
        try (JarFile jf = new JarFile(jar.toFile())) {
            return jf.getEntry("META-INF/vauban-bce-processed") != null;
        }
    }

    private record Pattern(String groupId, String artifactId) {
        static Pattern parse(String s) {
            int colon = s.indexOf(':');
            String g = colon >= 0 ? s.substring(0, colon) : s;
            String a = colon >= 0 ? s.substring(colon + 1) : "*";
            return new Pattern(g, a.isEmpty() ? "*" : a);
        }
        boolean matches(String g, String a) {
            return matchToken(groupId, g) && matchToken(artifactId, a);
        }
        private static boolean matchToken(String pattern, String value) {
            if ("*".equals(pattern)) return true;
            if (pattern.endsWith("*")) {
                return value.startsWith(pattern.substring(0, pattern.length() - 1));
            }
            return pattern.equals(value);
        }
    }
}
