/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.maven;

import io.vidocq.vauban.maven.modularize.ModularizedJars;
import io.vidocq.vauban.maven.modularize.Modularizer;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.lang.module.ModuleDescriptor;
import java.lang.module.ModuleFinder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.spi.ToolProvider;
import java.util.stream.Stream;

/**
 * Package a Vidocq application into a standalone <b>jlink</b> runtime image —
 * no pre-installed JRE required on target.
 *
 * <p>Output structure ({@code target/dist/} by default):
 * <pre>
 *   dist/
 *     bin/&lt;launcher&gt;        — startup script generated by jlink
 *     conf/ — vidocq.properties, logging.properties, ...
 *     lib/, legal/, release — jlink runtime image (modules + JDK)
 * </pre>
 *
 * <p>All dependency jars and the application artifact must be
 * <b>named Java modules</b> (presence of a {@code module-info.class}). TEA
 * automatic modules are rejected by {@code jlink}. Run {@code vauban:modularize}
 * first to patch the non-modular dependencies: this goal stages the copies it
 * produced in {@code target/vauban-modularized/} instead of the original jars.</p>
 */
@Mojo(name = "jlink",
      defaultPhase = LifecyclePhase.PACKAGE,
      requiresDependencyResolution = ResolutionScope.RUNTIME)
public class VidocqJlinkMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /** Java module containing the main class (e.g. {@code io.vidocq.runtime.examples.rest}). */
    @Parameter(property = "vidocq.mainModule", required = true)
    private String mainModule;

    /** Fully qualified main class (e.g. {@code io.vidocq.runtime.examples.rest.RestExampleApp}). */
    @Parameter(property = "vidocq.mainClass", required = true)
    private String mainClass;

    /** Name of the launcher generated in {@code dist/bin/} (default: {@code project.artifactId}). */
    @Parameter(defaultValue = "${project.artifactId}", property = "vidocq.launcher")
    private String launcher;

    /** Output directory of the jlink image (default: {@code target/dist}). */
    @Parameter(defaultValue = "${project.build.directory}/dist", property = "vidocq.distDir")
    private File distDir;

    /** Module staging directory before jlink (default: {@code target/jlink-mods}). */
    @Parameter(defaultValue = "${project.build.directory}/jlink-mods", readonly = true)
    private File modsDir;


    @Parameter(defaultValue = "${project.build.directory}", readonly = true)
    private File buildDir;

    @Parameter(defaultValue = "${project.build.outputDirectory}", readonly = true)
    private File classesDir;

    /** Strip debug info (default: true). */
    @Parameter(defaultValue = "true", property = "vidocq.stripDebug")
    private boolean stripDebug;

    /**
     * Skip the complete execution of the jlink goal (default: false).
     * Useful in CI to short-circuit the packaging when a dependency remains
     * temporarily an automatic module while waiting for its transition to Java Modules.
     */
    @Parameter(defaultValue = "false", property = "vidocq.jlink.skip")
    private boolean skip;

    /** jlink compression level ({@code zip-0} to {@code zip-9}, default: {@code zip-6}). */
    @Parameter(defaultValue = "zip-6", property = "vidocq.compress")
    private String compress;

    /**
     * Non-modular resources to copy into {@code dist/conf/}, relating to
     * {@code target/classes/}. Default: {@code vidocq.properties} and {@code logging.properties}
     * if they exist.
     */
    @Parameter(property = "vidocq.includeResources")
    private List<String> includeResources;

    @Override
    public void execute() throws MojoExecutionException {
        if (skip) {
            getLog().info("Vidocq jlink — skip (vidocq.jlink.skip=true).");
            return;
        }
        getLog().info("Vidocq jlink — main: " + mainModule + "/" + mainClass);
        try {
            stageModules();
            String addModules = resolveAddModules();
            runJlink(addModules);
            copyResources();
            getLog().info("jlink image ready: " + distDir.toPath().toAbsolutePath());
            getLog().info("Run with: " + distDir.toPath().toAbsolutePath() + "/bin/" + launcher);
        } catch (IOException | InterruptedException e) {
            throw new MojoExecutionException("Failed to create jlink image", e);
        }
    }

    private void stageModules() throws IOException {
        Path stage = modsDir.toPath();
        deleteRecursive(stage);
        Files.createDirectories(stage);

        Path appJar = project.getArtifact().getFile().toPath();
        Files.copy(appJar, stage.resolve(appJar.getFileName()), StandardCopyOption.REPLACE_EXISTING);

        for (var artifact : project.getArtifacts()) {
            File f = artifact.getFile();
            if (f != null && f.getName().endsWith(".jar")) {
                if (DevOnlyJars.isDevOnly(f.toPath())) {
                    getLog().warn(DevOnlyJars.droppedWarning(artifact.getArtifactId()));
                    continue;
                }
                // Prefer a sealed/repackaged copy (cassini-maven-plugin) when one exists for this
                // artifact: same module name, but the resource package is closed and the adapters are
                // published via `provides`. Staged under the ORIGINAL filename for consistency.
                File sealed = new File(new File(project.getBuild().getDirectory(), "cassini-repackaged"),
                        artifact.getArtifactId() + "-" + artifact.getVersion() + "-cassini.jar");
                Path src = sealed.isFile() ? sealed.toPath() : f.toPath();
                if (sealed.isFile()) {
                    getLog().info("Staging sealed copy of " + artifact.getArtifactId()
                            + " (resource package closed, adapters via provides)");
                }
                // Prefer the enriched copy vidocq:generate wrote (its generated code declared in its
                // descriptor), else the copy patched with a generated module-info by vauban:modularize:
                // jlink rejects automatic modules, so this is what makes a non-modular
                // dependency stageable at all.
                EnrichedJars.rebaseOnModularized(buildDir.toPath(), new EnrichedJars.Scanned(f.toPath(),
                        artifact.getArtifactId(), artifact.getGroupId() + ":" + artifact.getArtifactId() + ":"
                                + artifact.getVersion()), getLog()::info);
                Path modularized = EnrichedJars.resolve(buildDir.toPath(), f.toPath());
                if (!modularized.equals(f.toPath())) {
                    src = modularized;
                    getLog().info(EnrichedJars.isEnriched(buildDir.toPath(), f.toPath())
                            ? "Staging enriched copy of " + artifact.getArtifactId()
                                    + " (vidocq:generate added its generated code and declared it)"
                            : "Staging modularized copy of " + artifact.getArtifactId()
                                    + " (vauban:modularize generated its module descriptor)");
                }
                // Stage an enriched copy when vidocq:generate parked cross-module classes
                // for this dependency: the generated classes ship inside the module that
                // owns their package, so the image has no split package to reject.
                Path patchDir = JpmsPatches.patchDirFor(buildDir.toPath(), artifact.getArtifactId());
                if (!EnrichedJars.isEnriched(buildDir.toPath(), f.toPath()) && Files.isDirectory(patchDir)) {
                    JpmsPatches.enrich(src, patchDir, stage.resolve(f.getName()));
                    getLog().info("Staging enriched copy of " + artifact.getArtifactId()
                            + " (carries its generated classes, JPMS cross-module)");
                } else {
                    Files.copy(src, stage.resolve(f.getName()), StandardCopyOption.REPLACE_EXISTING);
                }
            }
        }

        // Check: All staged jars must be named modules.
        List<String> automatic = new ArrayList<>();
        for (var ref : ModuleFinder.of(stage).findAll()) {
            ModuleDescriptor md = ref.descriptor();
            if (md.isAutomatic()) {
                automatic.add(md.name() + " (" + ref.location().orElse(null) + ")");
            }
        }
        if (!automatic.isEmpty()) {
            throw new IOException(automaticModulesMessage(automatic, buildDir.toPath()));
        }
    }

    /**
     * The failure raised when jars stayed automatic in the staged image.
     *
     * <p>Telling the user to "run vauban:modularize" is actively wrong for a jar that
     * {@code modularize} <em>deliberately</em> left automatic — a {@code ServiceLoader} cycle has no
     * legal explicit descriptor, so running the goal again changes nothing. The report the goal
     * already wrote is therefore read back and its {@code kept automatic: … — <reason>} line quoted
     * for each such module; the generic hint is kept only for the modules it does not explain.
     *
     * @param names    one {@code <module name> (<location>)} entry per rejected module
     * @param buildDir the project {@code target/} directory, holding the modularize report
     */
    static String automaticModulesMessage(List<String> names, Path buildDir) {
        Map<String, String> kept = keptAutomaticReasons(buildDir);
        StringBuilder sb = new StringBuilder("jlink does not support automatic modules: ")
                .append(String.join(", ", names)).append('.');
        List<String> unexplained = new ArrayList<>();
        boolean anyKept = false;
        for (String entry : names) {
            String reason = kept.get(jarFileNameOf(entry));
            if (reason == null) {
                unexplained.add(entry);
            } else {
                anyKept = true;
                sb.append("\n  ").append(entry)
                        .append("\n      vauban:modularize kept it automatic on purpose: ").append(reason);
            }
        }
        if (anyKept) {
            sb.append("\n  A jar kept automatic has no legal explicit descriptor, so re-running")
                    .append(" vauban:modularize cannot fix it: exclude the artifact from the image,")
                    .append(" drop the dependency, or set vidocq.modularize.forceExplicit=true when")
                    .append(" you know the failing lookup is one your application never reaches.");
        }
        if (!unexplained.isEmpty()) {
            sb.append("\n  Convert into proper Java modules (add a module-info.java) — run")
                    .append(" vauban:modularize (mode all-automatic) before jlink, or exclude the")
                    .append(" artifact: ").append(String.join(", ", unexplained)).append('.');
        }
        return sb.toString();
    }

    /** {@code jar file name → reason} for every {@code kept automatic:} line of the report. */
    private static Map<String, String> keptAutomaticReasons(Path buildDir) {
        Path report = ModularizedJars.root(buildDir).resolve(Modularizer.REPORT_FILE_NAME);
        if (!Files.isRegularFile(report)) {
            return Map.of();
        }
        Map<String, String> reasons = new LinkedHashMap<>();
        try {
            for (String line : Files.readAllLines(report)) {
                String l = line.strip();
                if (!l.startsWith(Modularizer.KEPT_AUTOMATIC_PREFIX)) {
                    continue;
                }
                String rest = l.substring(Modularizer.KEPT_AUTOMATIC_PREFIX.length());
                int sep = rest.indexOf(" — ");
                if (sep > 0) {
                    reasons.put(rest.substring(0, sep).strip(), rest.substring(sep + 3).strip());
                }
            }
        } catch (IOException e) {
            // A report we cannot read only costs the extra explanation, never the failure itself.
            return Map.of();
        }
        return reasons;
    }

    /** {@code name (file:/…/foo-1.0.jar)} → {@code foo-1.0.jar}; the whole entry when it has none. */
    private static String jarFileNameOf(String entry) {
        int close = entry.lastIndexOf(')');
        String location = close < 0 ? entry : entry.substring(entry.lastIndexOf('(') + 1, close);
        int slash = location.lastIndexOf('/');
        return slash < 0 ? location : location.substring(slash + 1);
    }

    /** Resolves the full set of modules to include: user modules + transitive JDK (via jdeps). */
    private String resolveAddModules() throws IOException {
        Path stage = modsDir.toPath();
        Set<String> userModules = new LinkedHashSet<>();
        for (var ref : ModuleFinder.of(stage).findAll()) {
            userModules.add(ref.descriptor().name());
        }
        if (!userModules.contains(mainModule)) {
            throw new IOException("mainModule '" + mainModule + "' not found among staged modules: " + userModules);
        }

        // jdeps --print-module-deps on the app jar, with the jars staged in module-path,
        // returns the minimum list of modules (including JDK) required transitively.
        ToolProvider jdeps = ToolProvider.findFirst("jdeps")
                .orElseThrow(() -> new IOException("jdeps tool is not available in this JDK"));

        Path appJar = project.getArtifact().getFile().toPath();
        ByteArrayOutputStream stdout = new ByteArrayOutputStream();
        ByteArrayOutputStream stderr = new ByteArrayOutputStream();
        int rc;
        try (var ps = new PrintStream(stdout, true, StandardCharsets.UTF_8);
             var pe = new PrintStream(stderr, true, StandardCharsets.UTF_8)) {
            rc = jdeps.run(ps, pe,
                    "--module-path", stage.toString(),
                    "--multi-release", "25",
                    "--ignore-missing-deps",
                    "--print-module-deps",
                    appJar.toString());
        }
        if (rc != 0) {
            getLog().warn("jdeps stderr: " + stderr.toString(StandardCharsets.UTF_8));
            throw new IOException("jdeps failed (rc=" + rc + ")");
        }
        String jdepsOutput = stdout.toString(StandardCharsets.UTF_8).trim();
        Set<String> all = new LinkedHashSet<>(userModules);
        if (!jdepsOutput.isEmpty()) {
            for (String m : jdepsOutput.split(",")) {
                String t = m.trim();
                if (!t.isEmpty()) all.add(t);
            }
        }
        return String.join(",", all);
    }

    private void runJlink(String addModules) throws IOException, InterruptedException {
        Path output = distDir.toPath();
        deleteRecursive(output);

        String javaHome = System.getProperty("java.home");
        String modulePath = modsDir.toPath() + File.pathSeparator + javaHome + "/jmods";

        List<String> args = new ArrayList<>();
        args.add("--module-path"); args.add(modulePath);
        args.add("--add-modules"); args.add(addModules);
        args.add("--launcher"); args.add(launcher + "=" + mainModule + "/" + mainClass);
        args.add("--output"); args.add(output.toString());
        args.add("--no-header-files");
        args.add("--no-man-pages");
        if (stripDebug) args.add("--strip-debug");
        if (compress != null && !compress.isBlank()) {
            args.add("--compress=" + compress);
        }

        ToolProvider jlink = ToolProvider.findFirst("jlink")
                .orElseThrow(() -> new IOException("jlink tool is not available in this JDK"));
        getLog().info("Modules: " + addModules);
        int rc = jlink.run(System.out, System.err, args.toArray(new String[0]));
        if (rc != 0) {
            throw new IOException("jlink failed (rc=" + rc + ")");
        }
    }

    private void copyResources() throws IOException {
        List<String> names = (includeResources == null || includeResources.isEmpty())
                ? List.of("vidocq.properties", "logging.properties")
                : includeResources;
        Path conf = distDir.toPath().resolve("conf");
        Files.createDirectories(conf);
        for (String name : names) {
            Path src = classesDir.toPath().resolve(name);
            if (Files.isRegularFile(src)) {
                Files.copy(src, conf.resolve(name), StandardCopyOption.REPLACE_EXISTING);
                getLog().info("Copied resource: " + name + " -> conf/");
            }
        }
    }

    private static void deleteRecursive(Path root) throws IOException {
        if (!Files.exists(root)) return;
        try (Stream<Path> walk = Files.walk(root)) {
            walk.sorted(Comparator.reverseOrder()).forEach(p -> {
                try { Files.delete(p); } catch (IOException e) { throw new RuntimeException(e); }
            });
        }
    }
}
