package io.vidocq.runtime.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.lang.module.ModuleDescriptor;
import java.lang.module.ModuleFinder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.spi.ToolProvider;
import java.util.stream.Stream;

/**
 * Package a Vidocq application into a standalone <b>jlink</b> runtime image —
 * no pre-installed JRE required on target.
 *
 * <p>Output structure ({@code target/dist/} by default):
 * <pre>
 *   dist/
 *     bin/&lt;launcher&gt;        — startup script generated by jlink
 *     conf/ — vidocq.properties, logging.properties, ...
 *     lib/, legal/, release — jlink runtime image (modules + JDK)
 * </pre>
 *
 * <p>All dependency jars and the application artifact must be
 * <b>named JPMS modules</b> (presence of a {@code module-info.class}). TEA
 * automatic modules are rejected by {@code jlink}.</p>
 */
@Mojo(name = "jlink",
      defaultPhase = LifecyclePhase.PACKAGE,
      requiresDependencyResolution = ResolutionScope.RUNTIME)
public class VidocqJlinkMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /** Java module containing the main class (e.g. {@code io.vidocq.runtime.examples.rest}). */
    @Parameter(property = "vidocq.mainModule", required = true)
    private String mainModule;

    /** Fully qualified main class (e.g. {@code io.vidocq.runtime.examples.rest.RestExampleApp}). */
    @Parameter(property = "vidocq.mainClass", required = true)
    private String mainClass;

    /** Name of the launcher generated in {@code dist/bin/} (default: {@code project.artifactId}). */
    @Parameter(defaultValue = "${project.artifactId}", property = "vidocq.launcher")
    private String launcher;

    /** Output directory of the jlink image (default: {@code target/dist}). */
    @Parameter(defaultValue = "${project.build.directory}/dist", property = "vidocq.distDir")
    private File distDir;

    /** Module staging directory before jlink (default: {@code target/jlink-mods}). */
    @Parameter(defaultValue = "${project.build.directory}/jlink-mods", readonly = true)
    private File modsDir;


    @Parameter(defaultValue = "${project.build.directory}", readonly = true)
    private File buildDir;

    @Parameter(defaultValue = "${project.build.outputDirectory}", readonly = true)
    private File classesDir;

    /** Strip debug info (default: true). */
    @Parameter(defaultValue = "true", property = "vidocq.stripDebug")
    private boolean stripDebug;

    /**
     * Skip the complete execution of the jlink goal (default: false).
     * Useful in CI to short-circuit the packaging when a dependency remains
     * temporarily an automatic module while waiting for its transition to JPMS.
     */
    @Parameter(defaultValue = "false", property = "vidocq.jlink.skip")
    private boolean skip;

    /** jlink compression level ({@code zip-0} to {@code zip-9}, default: {@code zip-6}). */
    @Parameter(defaultValue = "zip-6", property = "vidocq.compress")
    private String compress;

    /**
     * Non-modular resources to copy into {@code dist/conf/}, relating to
     * {@code target/classes/}. Default: {@code vidocq.properties} and {@code logging.properties}
     * if they exist.
     */
    @Parameter(property = "vidocq.includeResources")
    private List<String> includeResources;

    @Override
    public void execute() throws MojoExecutionException {
        if (skip) {
            getLog().info("Vidocq jlink — skip (vidocq.jlink.skip=true).");
            return;
        }
        getLog().info("Vidocq jlink — main: " + mainModule + "/" + mainClass);
        try {
            stageModules();
            String addModules = resolveAddModules();
            runJlink(addModules);
            copyResources();
            getLog().info("jlink image ready: " + distDir.toPath().toAbsolutePath());
            getLog().info("Run with: " + distDir.toPath().toAbsolutePath() + "/bin/" + launcher);
        } catch (IOException | InterruptedException e) {
            throw new MojoExecutionException("Failed to create jlink image", e);
        }
    }

    private void stageModules() throws IOException {
        Path stage = modsDir.toPath();
        deleteRecursive(stage);
        Files.createDirectories(stage);

        Path appJar = project.getArtifact().getFile().toPath();
        Files.copy(appJar, stage.resolve(appJar.getFileName()), StandardCopyOption.REPLACE_EXISTING);

        for (var artifact : project.getArtifacts()) {
            File f = artifact.getFile();
            if (f != null && f.getName().endsWith(".jar")) {
                // Prefer a sealed/repackaged copy (cassini-maven-plugin) when one exists for this
                // artifact: same module name, but the resource package is closed and the adapters are
                // published via `provides`. Staged under the ORIGINAL filename for consistency.
                File sealed = new File(new File(project.getBuild().getDirectory(), "cassini-repackaged"),
                        artifact.getArtifactId() + "-" + artifact.getVersion() + "-cassini.jar");
                Path src = sealed.isFile() ? sealed.toPath() : f.toPath();
                if (sealed.isFile()) {
                    getLog().info("Staging sealed copy of " + artifact.getArtifactId()
                            + " (resource package closed, adapters via provides)");
                }
                Files.copy(src, stage.resolve(f.getName()), StandardCopyOption.REPLACE_EXISTING);
            }
        }

        // Check: All staged jars must be named modules.
        List<String> automatic = new ArrayList<>();
        for (var ref : ModuleFinder.of(stage).findAll()) {
            ModuleDescriptor md = ref.descriptor();
            if (md.isAutomatic()) {
                automatic.add(md.name() + " (" + ref.location().orElse(null) + ")");
            }
        }
        if (!automatic.isEmpty()) {
            throw new IOException("jlink does not support automatic modules: "
                    + String.join(", ", automatic)
                    + ". Convert these JARs into proper JPMS modules (add a module-info.java).");
        }
    }

    /** Resolves the full set of modules to include: user modules + transitive JDK (via jdeps). */
    private String resolveAddModules() throws IOException {
        Path stage = modsDir.toPath();
        Set<String> userModules = new LinkedHashSet<>();
        for (var ref : ModuleFinder.of(stage).findAll()) {
            userModules.add(ref.descriptor().name());
        }
        if (!userModules.contains(mainModule)) {
            throw new IOException("mainModule '" + mainModule + "' not found among staged modules: " + userModules);
        }

        // jdeps --print-module-deps on the app jar, with the jars staged in module-path,
        // returns the minimum list of modules (including JDK) required transitively.
        ToolProvider jdeps = ToolProvider.findFirst("jdeps")
                .orElseThrow(() -> new IOException("jdeps tool is not available in this JDK"));

        Path appJar = project.getArtifact().getFile().toPath();
        ByteArrayOutputStream stdout = new ByteArrayOutputStream();
        ByteArrayOutputStream stderr = new ByteArrayOutputStream();
        int rc;
        try (var ps = new PrintStream(stdout, true, StandardCharsets.UTF_8);
             var pe = new PrintStream(stderr, true, StandardCharsets.UTF_8)) {
            rc = jdeps.run(ps, pe,
                    "--module-path", stage.toString(),
                    "--multi-release", "25",
                    "--ignore-missing-deps",
                    "--print-module-deps",
                    appJar.toString());
        }
        if (rc != 0) {
            getLog().warn("jdeps stderr: " + stderr.toString(StandardCharsets.UTF_8));
            throw new IOException("jdeps failed (rc=" + rc + ")");
        }
        String jdepsOutput = stdout.toString(StandardCharsets.UTF_8).trim();
        Set<String> all = new LinkedHashSet<>(userModules);
        if (!jdepsOutput.isEmpty()) {
            for (String m : jdepsOutput.split(",")) {
                String t = m.trim();
                if (!t.isEmpty()) all.add(t);
            }
        }
        return String.join(",", all);
    }

    private void runJlink(String addModules) throws IOException, InterruptedException {
        Path output = distDir.toPath();
        deleteRecursive(output);

        String javaHome = System.getProperty("java.home");
        String modulePath = modsDir.toPath() + File.pathSeparator + javaHome + "/jmods";

        List<String> args = new ArrayList<>();
        args.add("--module-path"); args.add(modulePath);
        args.add("--add-modules"); args.add(addModules);
        args.add("--launcher"); args.add(launcher + "=" + mainModule + "/" + mainClass);
        args.add("--output"); args.add(output.toString());
        args.add("--no-header-files");
        args.add("--no-man-pages");
        if (stripDebug) args.add("--strip-debug");
        if (compress != null && !compress.isBlank()) {
            args.add("--compress=" + compress);
        }

        ToolProvider jlink = ToolProvider.findFirst("jlink")
                .orElseThrow(() -> new IOException("jlink tool is not available in this JDK"));
        getLog().info("Modules: " + addModules);
        int rc = jlink.run(System.out, System.err, args.toArray(new String[0]));
        if (rc != 0) {
            throw new IOException("jlink failed (rc=" + rc + ")");
        }
    }

    private void copyResources() throws IOException {
        List<String> names = (includeResources == null || includeResources.isEmpty())
                ? List.of("vidocq.properties", "logging.properties")
                : includeResources;
        Path conf = distDir.toPath().resolve("conf");
        Files.createDirectories(conf);
        for (String name : names) {
            Path src = classesDir.toPath().resolve(name);
            if (Files.isRegularFile(src)) {
                Files.copy(src, conf.resolve(name), StandardCopyOption.REPLACE_EXISTING);
                getLog().info("Copied resource: " + name + " -> conf/");
            }
        }
    }

    private static void deleteRecursive(Path root) throws IOException {
        if (!Files.exists(root)) return;
        try (Stream<Path> walk = Files.walk(root)) {
            walk.sorted(Comparator.reverseOrder()).forEach(p -> {
                try { Files.delete(p); } catch (IOException e) { throw new RuntimeException(e); }
            });
        }
    }
}
