package io.vidocq.mpserver.examples.mansart;

import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Instance;
import jakarta.inject.Inject;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Demo-only schema bootstrap. {@code @ApplicationScoped} + {@code @PostConstruct} runs once at
 * Vauban container start, after the {@link DataSource} bean published by the mansart-pool extension
 * is available. In a real application you would use Flyway / Liquibase or your DB migration tool
 * of choice — this is intentionally minimal so the example stays runnable without extra deps.
 */
@ApplicationScoped
public class SchemaInitializer {

    // Indirect via Instance<> so the Vauban APT does not statically reject the @Inject : the
    // DataSource bean is contributed by mansart-pool-extension at runtime and not visible to the
    // compile-time index of this module.
    @Inject
    Instance<DataSource> dataSourceInstance;

    @PostConstruct
    void initSchema() {
        DataSource dataSource = dataSourceInstance.get();
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"products\"");
            s.execute("CREATE TABLE \"products\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL,"
                    + "  \"price\" DOUBLE NOT NULL"
                    + ")");
            s.execute("INSERT INTO \"products\"(\"name\", \"price\") VALUES "
                    + "('Espresso', 2.50), ('Cappuccino', 3.50), ('Latte', 4.00)");
        } catch (SQLException e) {
            throw new IllegalStateException("Failed to initialize H2 demo schema", e);
        }
    }
}
