package io.vidocq.mpserver.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Génère un {@code Dockerfile} qui empaquette l'image runtime jlink dans une
 * image Docker minimale (sans JRE supplémentaire — jlink contient son propre
 * runtime).
 *
 * <p>Par défaut le Mojo se contente de générer le {@code Dockerfile} dans
 * {@code target/} et d'expliquer comment le builder. Si {@code &lt;build&gt;true&lt;/build&gt;}
 * et que le binaire {@code docker} est disponible, le Mojo lance
 * {@code docker build -t &lt;imageTag&gt; -f target/Dockerfile target/}.</p>
 *
 * <h3>Image de base recommandée</h3>
 * <p>{@code gcr.io/distroless/base-debian12:nonroot} (~20 MB) — pas de JRE
 * (jlink fournit le runtime), pas de shell, user non-root par défaut. Pour
 * un debug interactif : {@code gcr.io/distroless/base-debian12:debug}.</p>
 */
@Mojo(name = "docker",
      defaultPhase = LifecyclePhase.PACKAGE,
      requiresDependencyResolution = ResolutionScope.RUNTIME)
public class VidocqDockerMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /**
     * Image runtime jlink en entrée. Défaut : {@code target/dist} (sortie de
     * {@code vidocq:jlink}). Doit être un chemin relatif au {@code target/}
     * Maven (le Dockerfile généré utilise un COPY relatif).
     */
    @Parameter(defaultValue = "${project.build.directory}/dist", property = "vidocq.runtimeImage")
    private File runtimeImage;

    /** Image de base Docker. Défaut : {@code gcr.io/distroless/base-debian12:nonroot}. */
    @Parameter(defaultValue = "gcr.io/distroless/base-debian12:nonroot", property = "vidocq.docker.baseImage")
    private String baseImage;

    /** Tag de l'image générée. Défaut : {@code &lt;artifactId&gt;:&lt;version&gt;}. */
    @Parameter(defaultValue = "${project.artifactId}:${project.version}", property = "vidocq.docker.imageTag")
    private String imageTag;

    /** Port exposé. Défaut : 8080. */
    @Parameter(defaultValue = "8080", property = "vidocq.docker.exposedPort")
    private int exposedPort;

    /** Nom du launcher dans {@code dist/bin/}. Défaut : {@code project.artifactId}. */
    @Parameter(defaultValue = "${project.artifactId}", property = "vidocq.launcher")
    private String launcher;

    /**
     * Si {@code true}, lance {@code docker build} en sus de la génération.
     * Défaut : {@code false} (le user lance lui-même quand il veut).
     */
    @Parameter(defaultValue = "false", property = "vidocq.docker.build")
    private boolean build;

    @Parameter(defaultValue = "${project.build.directory}", readonly = true)
    private File buildDir;

    @Override
    public void execute() throws MojoExecutionException {
        if (!runtimeImage.isDirectory()) {
            throw new MojoExecutionException(
                    "runtimeImage introuvable : " + runtimeImage
                            + ". Lance d'abord vidocq:jlink (ou pointe runtimeImage sur une image existante).");
        }

        Path target = buildDir.toPath();
        Path dockerfile = target.resolve("Dockerfile");

        // Le Dockerfile est dans target/, le COPY référence dist/ relatif à
        // target/ (= build context).
        String distRel = target.relativize(runtimeImage.toPath()).toString();

        String content = """
                # Generated by vidocq-mps-maven-plugin (vidocq:docker)
                # Build context : target/
                # Build         : docker build -t %s -f target/Dockerfile target/
                # Run           : docker run --rm -p %d:%d %s

                FROM %s

                COPY %s /opt/app/

                WORKDIR /opt/app
                EXPOSE %d
                ENTRYPOINT ["/opt/app/bin/%s"]
                """.formatted(imageTag, exposedPort, exposedPort, imageTag,
                        baseImage, distRel, exposedPort, launcher);

        try {
            Files.writeString(dockerfile, content);
            getLog().info("Dockerfile généré : " + dockerfile.toAbsolutePath());
            getLog().info("Build avec : docker build -t " + imageTag + " -f " + dockerfile + " " + target);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to write Dockerfile", e);
        }

        if (build) {
            runDockerBuild(dockerfile, target);
        }
    }

    private void runDockerBuild(Path dockerfile, Path context) throws MojoExecutionException {
        try {
            ProcessBuilder pb = new ProcessBuilder("docker", "build",
                    "-t", imageTag,
                    "-f", dockerfile.toString(),
                    context.toString())
                    .inheritIO();
            getLog().info("Running: " + String.join(" ", pb.command()));
            int rc = pb.start().waitFor();
            if (rc != 0) {
                throw new MojoExecutionException("docker build a échoué (rc=" + rc + ")");
            }
            getLog().info("Image Docker construite : " + imageTag);
        } catch (IOException e) {
            throw new MojoExecutionException(
                    "Impossible de lancer 'docker build' (binaire docker introuvable ?). "
                            + "Lance manuellement : docker build -t " + imageTag + " -f "
                            + dockerfile + " " + context, e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new MojoExecutionException("docker build interrompu", e);
        }
    }
}
