module io.vidocq.runtime.examples.knock {
    requires java.logging;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.ws.rs;
    requires jakarta.annotation;
    requires jakarta.json.bind;

    requires io.vidocq.runtime.core;
    requires io.vidocq.runtime.spi;
    requires io.vidocq.runtime.ext.rest.cassini;
    // Pulls all of knock transitively (api/core/cdi-vauban/jaxrs) and activates the
    // @Liveness/@Readiness/@Startup discovery BCE + the auto-mounted KnockHealthResource.
    requires io.vidocq.runtime.ext.knock;
    requires io.vidocq.knock.api;            // HealthCheckRegistry / SPI
    // MP Health spec API. JPMS module name is `microprofile.health.api` (Vidocq fork with
    // module-info); the package is org.eclipse.microprofile.health. Brings HealthCheck /
    // HealthCheckResponse / @Liveness. Re-exported transitively by io.vidocq.knock.api.
    requires microprofile.health.api;

    requires io.vidocq.cassini.api;
    requires io.vidocq.chappe.api;
    requires io.vidocq.vauban.core;

    // CDI/JAX-RS introspection of this module's own beans (AppLivenessCheck).
    opens io.vidocq.runtime.examples.knock;

    // Generated by Vauban APT: in-module instantiation of this module's beans on the module path.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.runtime.examples.knock._VaubanComponents;

    exports io.vidocq.runtime.logging to java.logging;
}
