/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
module io.vidocq.runtime.examples.knock {
    requires java.logging;
    requires jakarta.cdi;
    requires jakarta.inject;
    requires jakarta.ws.rs;
    requires jakarta.annotation;
    requires jakarta.json.bind;

    requires io.vidocq.runtime.core;
    requires io.vidocq.runtime.spi;
    requires io.vidocq.runtime.extensions.jakartaee.core.cassini;
    // Pulls all of knock transitively (api/core/cdi-vauban/jaxrs) and activates the
    // @Liveness/@Readiness/@Startup discovery BCE + the auto-mounted KnockHealthResource.
    requires io.vidocq.runtime.extensions.microprofile.knock;
    requires io.vidocq.knock.api;            // HealthCheckRegistry / SPI
    // MP Health spec API. JPMS module name is `microprofile.health.api` (Vidocq fork with
    // module-info); the package is org.eclipse.microprofile.health. Brings HealthCheck /
    // HealthCheckResponse / @Liveness. Re-exported transitively by io.vidocq.knock.api.
    requires microprofile.health.api;

    requires io.vidocq.cassini.api;
    requires io.vidocq.chappe.api;
    requires io.vidocq.vauban.core;

    // CDI/JAX-RS introspection of this module's own beans (AppLivenessCheck).
    opens io.vidocq.runtime.examples.knock;

    // Generated by Vauban APT: in-module instantiation of this module's beans on the module path.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.runtime.examples.knock._VaubanComponents;

    exports io.vidocq.runtime.logging to java.logging;
}
