/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
import java.nio.file.Files
import java.nio.file.Path

Path root = basedir.toPath()
Closure<byte[]> bytes = { String path -> Files.readAllBytes(root.resolve(path)) }
assert Arrays.equals(bytes('.run/AlphaApp.run.xml'), bytes('seed/AlphaApp.txt')) :
        'the hand-written file is left untouched:\n' + root.resolve('.run/AlphaApp.run.xml').toFile().text
assert Arrays.equals(bytes('.run/BetaApp.run.xml'), bytes('expected/BetaApp.txt')) :
        'the unmarked file with the expected content is adopted:\n' + root.resolve('.run/BetaApp.run.xml').toFile().text
String log = root.resolve('build.log').toFile().text
assert log.contains('[WARNING] Vidocq idea: .run/AlphaApp.run.xml belongs to you: it was not generated by vidocq:idea')
assert log.contains('Vidocq idea: updated .run/BetaApp.run.xml, marker added (com.example.it:beta, main class com.example.beta.BetaApp, IntelliJ module beta)')
assert log.contains('Vidocq idea: 2 run configuration(s): 1 updated, 1 left untouched')
assert log.contains("The application runs on the 'temurin-25' SDK") : 'vidocq.idea.jre is read from the top-level pom'
assert log.contains('are up to date; 1 belong(s) to you and were not checked.')
return true
