/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.maven.idea;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Locale;
import java.util.Optional;

/**
 * Renders an IntelliJ IDEA shared run configuration ({@code .run/<name>.run.xml}) for a Vidocq application,
 * in one of two {@linkplain Kind kinds}: the {@link Kind#MAVEN Maven} kind (the default), a Maven run of
 * {@value #DEV_GOAL}, {@value #RUN_GOAL} or a Remote JVM Debug run (Vidocq/vidocq#143), or the
 * {@link Kind#APPLICATION Application} kind, a run of the main class.
 *
 * <p>The body is written the way IntelliJ serialises a run configuration stored as a project file, so
 * that IntelliJ's own re-serialisation of a loaded file equals it and IntelliJ never rewrites the file
 * for formatting alone (IntelliJ 2026.2: {@code RCInArbitraryFileManager} compares digests of its
 * re-serialisation; {@code JDOMUtil} writes UTF-8, 2-space indentation, {@code " />"}, LF, no XML
 * declaration and nothing after the root element; {@code JvmMainMethodRunConfigurationOptions} omits
 * options left at their default and orders the others by name).
 *
 * <p>A generated file is a marker comment line followed by the body. The marker carries the SHA-256 of
 * the body: a file whose marker still matches its body was not edited since {@code vidocq:idea} wrote it.
 * IntelliJ ignores the comment when it loads the file and drops it when it saves a changed configuration.
 */
final class RunConfigurationRenderer {

    private static final String MARKER_TEXT =
            "Generated by vidocq:idea. Run \"mvn vidocq:idea\" to update it; once edited, it is left alone.";

    /** The goal an IntelliJ Maven run configuration runs, packaged behaviour (Vidocq/vidocq#143). */
    static final String RUN_GOAL = "vidocq:run";

    /** The goal the main, Dev configuration runs: console, reload, continuous testing (Vidocq/vidocq#143). */
    static final String DEV_GOAL = "vidocq:dev";

    /** Appended to the configuration name of the packaged-behaviour Maven configuration (Vidocq/vidocq#143). */
    static final String PACKAGED_SUFFIX = " (packaged)";

    /** Appended to the configuration name of the Remote JVM Debug configuration (Vidocq/vidocq#143). */
    static final String DEBUG_SUFFIX = " (debug)";

    /** What {@code vidocq.idea.kind} asks for. */
    enum Kind {
        /**
         * An IntelliJ <b>Maven</b> run configuration of {@value #RUN_GOAL} on the application's own pom, the
         * default: Maven compiles, indexes and forks the JVM exactly as on the command line, so the run can
         * never miss the bean index of the dependency jars the IDE build knows nothing about.
         */
        MAVEN,
        /**
         * An IntelliJ <b>Application</b> run configuration of the main class, with Make and
         * {@code vidocq:generate} before launch.
         */
        APPLICATION;

        /** Parses {@code vidocq.idea.kind}; empty for an unknown value, {@link #MAVEN} for none. */
        static Optional<Kind> parse(String value) {
            if (value == null || value.isBlank()) {
                return Optional.of(MAVEN);
            }
            return switch (value.strip().toLowerCase(Locale.ROOT)) {
                case "maven" -> Optional.of(MAVEN);
                case "application" -> Optional.of(APPLICATION);
                default -> Optional.empty();
            };
        }

        /** The value {@code vidocq.idea.kind} takes for this kind. */
        String property() {
            return name().toLowerCase(Locale.ROOT);
        }
    }

    private RunConfigurationRenderer() {
    }

    /** The file name IntelliJ gives a shared run configuration of that name ({@code sanitizeFileName}). */
    static String fileName(String configurationName) {
        StringBuilder name = new StringBuilder(configurationName.length());
        for (int i = 0; i < configurationName.length(); i++) {
            char c = configurationName.charAt(i);
            name.append("/\\?<>:*|\"".indexOf(c) >= 0 || Character.isISOControl(c) ? '_' : c);
        }
        return name.substring(0, Math.min(name.length(), 255)) + ".run.xml";
    }

    /** The marker line, then the body. */
    static String file(IdeaApplication application, Kind kind, String jre, boolean generateBeforeLaunch) {
        String body = body(application, kind, jre, generateBeforeLaunch);
        return markerLine(body) + "\n" + body;
    }

    /** The marker comment for a body; it never contains {@code --}, which XML forbids inside a comment. */
    static String markerLine(String body) {
        return "<!-- " + MARKER_TEXT + " sha256:" + sha256(body) + " -->";
    }

    /** The run configuration of that kind; {@code generateBeforeLaunch} only concerns {@link Kind#APPLICATION}. */
    static String body(IdeaApplication application, Kind kind, String jre, boolean generateBeforeLaunch) {
        return kind == Kind.MAVEN
                ? mavenBody(application, jre, RUN_GOAL, application.configurationName())
                : applicationBody(application, jre, generateBeforeLaunch);
    }

    /**
     * A Maven run configuration of {@code goal} on the application's pom, run in the project directory, named
     * {@code name}. {@code jre} becomes the Maven runner JRE, which is also the JDK the application runs on:
     * the goal forks it from the {@code java.home} of the JVM running Maven.
     *
     * <p>Element order and the options left at their default are those of IntelliJ's own serialisation
     * ({@code XmlSerializer.serialize(MavenRunConfiguration$MavenSettings)} of IntelliJ IDEA 2026.2.3,
     * measured): a file it re-serialises to itself is one it never rewrites. IntelliJ disables its Build
     * step for a Maven configuration, so nothing runs before launch — which is the point of this kind.
     */
    static String mavenBody(IdeaApplication application, String jre, String goal, String name) {
        StringBuilder xml = new StringBuilder(1100);
        xml.append("<component name=\"ProjectRunConfigurationManager\">\n");
        xml.append("  <configuration default=\"false\" name=\"").append(escapeAttribute(name))
                .append("\" type=\"MavenRunConfiguration\" factoryName=\"Maven\">\n");
        xml.append("    <MavenSettings>\n");
        // Left null: a run configuration that carries its own MavenGeneralSettings replaces the user's
        // Maven settings (settings file, local repository, offline, threads) with what it holds.
        xml.append("      <option name=\"myGeneralSettings\" />\n");
        if (jre == null) {
            xml.append("      <option name=\"myRunnerSettings\" />\n");
        } else {
            xml.append("      <option name=\"myRunnerSettings\">\n");
            xml.append("        <MavenRunnerSettings>\n");
            xml.append("          <option name=\"delegateBuildToMaven\" value=\"false\" />\n");
            xml.append("          <option name=\"environmentProperties\">\n");
            xml.append("            <map />\n");
            xml.append("          </option>\n");
            xml.append("          <option name=\"jreName\" value=\"").append(escapeAttribute(jre)).append("\" />\n");
            xml.append("          <option name=\"mavenProperties\">\n");
            xml.append("            <map />\n");
            xml.append("          </option>\n");
            xml.append("          <option name=\"passParentEnv\" value=\"true\" />\n");
            xml.append("          <option name=\"skipTests\" value=\"false\" />\n");
            xml.append("          <option name=\"vmOptions\" value=\"\" />\n");
            xml.append("        </MavenRunnerSettings>\n");
            xml.append("      </option>\n");
        }
        xml.append("      <option name=\"myRunnerParameters\">\n");
        xml.append("        <MavenRunnerParameters>\n");
        xml.append("          <option name=\"cmdOptions\" />\n");
        xml.append("          <option name=\"profiles\">\n");
        xml.append("            <set />\n");
        xml.append("          </option>\n");
        xml.append("          <option name=\"goals\">\n");
        xml.append("            <list>\n");
        xml.append("              <option value=\"").append(goal).append("\" />\n");
        xml.append("            </list>\n");
        xml.append("          </option>\n");
        xml.append("          <option name=\"multimoduleDir\" />\n");
        // -f <pom>: the goal runs on the application's own pom, whatever the project directory is.
        xml.append("          <option name=\"pomFileName\" value=\"").append(escapeAttribute(application.pomPath()))
                .append("\" />\n");
        xml.append("          <option name=\"profilesMap\">\n");
        xml.append("            <map />\n");
        xml.append("          </option>\n");
        xml.append("          <option name=\"projectsCmdOptionValues\">\n");
        xml.append("            <list />\n");
        xml.append("          </option>\n");
        xml.append("          <option name=\"resolveToWorkspace\" value=\"false\" />\n");
        xml.append("          <option name=\"workingDirPath\" value=\"$PROJECT_DIR$\" />\n");
        xml.append("        </MavenRunnerParameters>\n");
        xml.append("      </option>\n");
        xml.append("    </MavenSettings>\n");
        xml.append("    <method v=\"2\" />\n");
        xml.append("  </configuration>\n");
        xml.append("</component>");
        return xml.toString();
    }

    /**
     * An Application run configuration: Make, then (unless disabled) {@code vidocq:generate} on the
     * application's pom before launch; the JDK is left to IntelliJ (the module SDK) unless {@code jre}
     * names one.
     */
    private static String applicationBody(IdeaApplication application, String jre, boolean generateBeforeLaunch) {
        StringBuilder xml = new StringBuilder(700);
        xml.append("<component name=\"ProjectRunConfigurationManager\">\n");
        xml.append("  <configuration default=\"false\" name=\"").append(escapeAttribute(application.configurationName()))
                .append("\" type=\"Application\" factoryName=\"Application\">\n");
        if (jre != null) {
            xml.append("    <option name=\"ALTERNATIVE_JRE_PATH\" value=\"").append(escapeAttribute(jre)).append("\" />\n");
            xml.append("    <option name=\"ALTERNATIVE_JRE_PATH_ENABLED\" value=\"true\" />\n");
        }
        // IntelliJ stores and matches the qualified name, with dots for a nested class.
        xml.append("    <option name=\"MAIN_CLASS_NAME\" value=\"")
                .append(escapeAttribute(application.mainClass().replace('$', '.'))).append("\" />\n");
        xml.append("    <module name=\"").append(escapeAttribute(application.moduleName())).append("\" />\n");
        xml.append("    <method v=\"2\">\n");
        xml.append("      <option name=\"Make\" enabled=\"true\" />\n");
        if (generateBeforeLaunch) {
            xml.append("      <option name=\"Maven.BeforeRunTask\" enabled=\"true\" file=\"$PROJECT_DIR$/")
                    .append(escapeAttribute(application.pomPath())).append("\" goal=\"")
                    .append(escapeAttribute(application.generateGoal())).append("\" />\n");
        }
        xml.append("    </method>\n");
        xml.append("  </configuration>\n");
        xml.append("</component>");
        return xml.toString();
    }

    /** A Remote JVM Debug configuration that attaches to the debug agent of vidocq:dev (Vidocq/vidocq#143). */
    static String debugBody(String name, String host, int port) {
        StringBuilder xml = new StringBuilder(500);
        xml.append("<component name=\"ProjectRunConfigurationManager\">\n");
        xml.append("  <configuration default=\"false\" name=\"").append(escapeAttribute(name))
                .append("\" type=\"Remote\">\n");
        xml.append("    <option name=\"USE_SOCKET_TRANSPORT\" value=\"true\" />\n");
        xml.append("    <option name=\"SERVER_MODE\" value=\"false\" />\n");
        xml.append("    <option name=\"SHMEM_ADDRESS\" />\n");
        xml.append("    <option name=\"HOST\" value=\"").append(escapeAttribute(host)).append("\" />\n");
        xml.append("    <option name=\"PORT\" value=\"").append(port).append("\" />\n");
        xml.append("    <option name=\"AUTO_RESTART\" value=\"false\" />\n");
        xml.append("    <RunnerSettings RunnerId=\"Debug\">\n");
        xml.append("      <option name=\"DEBUG_PORT\" value=\"").append(port).append("\" />\n");
        xml.append("      <option name=\"LOCAL\" value=\"false\" />\n");
        xml.append("    </RunnerSettings>\n");
        xml.append("    <method v=\"2\" />\n");
        xml.append("  </configuration>\n");
        xml.append("</component>");
        return xml.toString();
    }

    /** Escapes an attribute value as IntelliJ's {@code JDOMUtil} does; apostrophes are kept. */
    static String escapeAttribute(String value) {
        StringBuilder escaped = new StringBuilder(value.length() + 16);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '&' -> escaped.append("&amp;");
                case '<' -> escaped.append("&lt;");
                case '>' -> escaped.append("&gt;");
                case '"' -> escaped.append("&quot;");
                case '\n' -> escaped.append("&#10;");
                case '\r' -> escaped.append("&#13;");
                case '\t' -> escaped.append("&#9;");
                default -> escaped.append(c);
            }
        }
        return escaped.toString();
    }

    /** Lower-case hexadecimal SHA-256 of the UTF-8 bytes of a text. */
    static String sha256(String text) {
        try {
            return HexFormat.of().formatHex(
                    MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is a mandatory JDK algorithm", e);
        }
    }
}
