/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.maven.idea;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * Renders an IntelliJ IDEA shared run configuration ({@code .run/<name>.run.xml}) for a Vidocq application.
 *
 * <p>The body is written the way IntelliJ serialises a run configuration stored as a project file, so
 * that IntelliJ's own re-serialisation of a loaded file equals it and IntelliJ never rewrites the file
 * for formatting alone (IntelliJ 2026.2: {@code RCInArbitraryFileManager} compares digests of its
 * re-serialisation; {@code JDOMUtil} writes UTF-8, 2-space indentation, {@code " />"}, LF, no XML
 * declaration and nothing after the root element; {@code JvmMainMethodRunConfigurationOptions} omits
 * options left at their default and orders the others by name).
 *
 * <p>A generated file is a marker comment line followed by the body. The marker carries the SHA-256 of
 * the body: a file whose marker still matches its body was not edited since {@code vidocq:idea} wrote it.
 * IntelliJ ignores the comment when it loads the file and drops it when it saves a changed configuration.
 */
final class RunConfigurationRenderer {

    private static final String MARKER_TEXT =
            "Generated by vidocq:idea. Run \"mvn vidocq:idea\" to update it; once edited, it is left alone.";

    private RunConfigurationRenderer() {
    }

    /** The file name IntelliJ gives a shared run configuration of that name ({@code sanitizeFileName}). */
    static String fileName(String configurationName) {
        StringBuilder name = new StringBuilder(configurationName.length());
        for (int i = 0; i < configurationName.length(); i++) {
            char c = configurationName.charAt(i);
            name.append("/\\?<>:*|\"".indexOf(c) >= 0 || Character.isISOControl(c) ? '_' : c);
        }
        return name.substring(0, Math.min(name.length(), 255)) + ".run.xml";
    }

    /** The marker line, then the body. */
    static String file(IdeaApplication application, String jre, boolean generateBeforeLaunch) {
        String body = body(application, jre, generateBeforeLaunch);
        return markerLine(body) + "\n" + body;
    }

    /** The marker comment for a body; it never contains {@code --}, which XML forbids inside a comment. */
    static String markerLine(String body) {
        return "<!-- " + MARKER_TEXT + " sha256:" + sha256(body) + " -->";
    }

    /**
     * The run configuration: Make, then (unless disabled) {@code vidocq:generate} on the application's
     * pom before launch; the JDK is left to IntelliJ (the module SDK) unless {@code jre} names one.
     */
    static String body(IdeaApplication application, String jre, boolean generateBeforeLaunch) {
        StringBuilder xml = new StringBuilder(700);
        xml.append("<component name=\"ProjectRunConfigurationManager\">\n");
        xml.append("  <configuration default=\"false\" name=\"").append(escapeAttribute(application.configurationName()))
                .append("\" type=\"Application\" factoryName=\"Application\">\n");
        if (jre != null) {
            xml.append("    <option name=\"ALTERNATIVE_JRE_PATH\" value=\"").append(escapeAttribute(jre)).append("\" />\n");
            xml.append("    <option name=\"ALTERNATIVE_JRE_PATH_ENABLED\" value=\"true\" />\n");
        }
        // IntelliJ stores and matches the qualified name, with dots for a nested class.
        xml.append("    <option name=\"MAIN_CLASS_NAME\" value=\"")
                .append(escapeAttribute(application.mainClass().replace('$', '.'))).append("\" />\n");
        xml.append("    <module name=\"").append(escapeAttribute(application.moduleName())).append("\" />\n");
        xml.append("    <method v=\"2\">\n");
        xml.append("      <option name=\"Make\" enabled=\"true\" />\n");
        if (generateBeforeLaunch) {
            xml.append("      <option name=\"Maven.BeforeRunTask\" enabled=\"true\" file=\"$PROJECT_DIR$/")
                    .append(escapeAttribute(application.pomPath())).append("\" goal=\"")
                    .append(escapeAttribute(application.generateGoal())).append("\" />\n");
        }
        xml.append("    </method>\n");
        xml.append("  </configuration>\n");
        xml.append("</component>");
        return xml.toString();
    }

    /** Escapes an attribute value as IntelliJ's {@code JDOMUtil} does; apostrophes are kept. */
    static String escapeAttribute(String value) {
        StringBuilder escaped = new StringBuilder(value.length() + 16);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '&' -> escaped.append("&amp;");
                case '<' -> escaped.append("&lt;");
                case '>' -> escaped.append("&gt;");
                case '"' -> escaped.append("&quot;");
                case '\n' -> escaped.append("&#10;");
                case '\r' -> escaped.append("&#13;");
                case '\t' -> escaped.append("&#9;");
                default -> escaped.append(c);
            }
        }
        return escaped.toString();
    }

    /** Lower-case hexadecimal SHA-256 of the UTF-8 bytes of a text. */
    static String sha256(String text) {
        try {
            return HexFormat.of().formatHex(
                    MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is a mandatory JDK algorithm", e);
        }
    }
}
