/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.runtime.maven.idea;

import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Decides, for a file of {@code .run/}, whether {@code vidocq:idea} owns it and what it would do to it.
 *
 * <p>Contents are compared after normalisation (UTF-8, {@code \r\n} read as {@code \n}, trailing newlines
 * ignored), so a checkout with {@code core.autocrlf} or an editor that adds a final newline is not an
 * edit. The marker is recognised by a pattern that tolerates future wordings; only its hash matters.
 */
final class RunConfigurationFiles {

    private static final Pattern MARKER = Pattern.compile("^<!-- Generated by vidocq:idea\\b.*\\bsha256:([0-9a-f]{64}) -->$");
    private static final Pattern JRE_PATH = Pattern.compile(
            "^\\s*<option name=\"ALTERNATIVE_JRE_PATH\" value=\"([^\"]*)\"\\s*/>\\s*$", Pattern.MULTILINE);
    private static final Pattern JRE_ENABLED = Pattern.compile(
            "^\\s*<option name=\"ALTERNATIVE_JRE_PATH_ENABLED\" value=\"true\"\\s*/>\\s*$", Pattern.MULTILINE);
    private static final Pattern JRE_NAME = Pattern.compile(
            "^\\s*<option name=\"jreName\" value=\"([^\"]*)\"\\s*/>\\s*$", Pattern.MULTILINE);

    /** What a file on disk is, compared with the body {@code vidocq:idea} would write. */
    enum State {
        /** No file: a write creates it, a check fails. */
        MISSING,
        /** Valid marker and expected body: nothing to do. */
        UNCHANGED,
        /** Valid marker, another body: a write updates it, a check fails. */
        OUTDATED,
        /** Expected body without marker: a write adds the marker, a check fails. */
        UNMARKED,
        /** Marker whose hash no longer matches the body: edited since, left to the user. */
        EDITED,
        /** No marker and another body (written by hand, or saved by IntelliJ): left to the user. */
        FOREIGN;

        /** Whether a write changes the file, which is exactly when a check fails. */
        boolean writes() {
            return this == MISSING || this == OUTDATED || this == UNMARKED;
        }

        /** Whether the file belongs to the user and is never touched. */
        boolean userOwned() {
            return this == EDITED || this == FOREIGN;
        }
    }

    private RunConfigurationFiles() {
    }

    /** Classifies the bytes on disk ({@code null} when there is no file) against the expected body. */
    static State classify(byte[] onDisk, String expectedBody) {
        if (onDisk == null) {
            return State.MISSING;
        }
        String content;
        try {
            content = normalize(StandardCharsets.UTF_8.newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(onDisk))
                    .toString());
        } catch (CharacterCodingException e) {
            return State.FOREIGN;
        }
        int newline = content.indexOf('\n');
        Matcher marker = MARKER.matcher(newline < 0 ? content : content.substring(0, newline));
        if (!marker.matches()) {
            return content.equals(expectedBody) ? State.UNMARKED : State.FOREIGN;
        }
        String body = newline < 0 ? "" : content.substring(newline + 1);
        if (!marker.group(1).equals(RunConfigurationRenderer.sha256(body))) {
            return State.EDITED;
        }
        return body.equals(expectedBody) ? State.UNCHANGED : State.OUTDATED;
    }

    /** Whether the file starts with a {@code vidocq:idea} marker, valid or not. */
    static boolean isGenerated(byte[] onDisk) {
        String content = normalize(new String(onDisk, StandardCharsets.UTF_8));
        int newline = content.indexOf('\n');
        return MARKER.matcher(newline < 0 ? content : content.substring(0, newline)).matches();
    }

    /** The normalised content without its marker line, for a diff. */
    static String shownBody(byte[] onDisk) {
        String content = normalize(new String(onDisk, StandardCharsets.UTF_8));
        int newline = content.indexOf('\n');
        if (MARKER.matcher(newline < 0 ? content : content.substring(0, newline)).matches()) {
            return newline < 0 ? "" : content.substring(newline + 1);
        }
        return content;
    }

    /**
     * The JDK a file pins, as IntelliJ stores it: {@code ALTERNATIVE_JRE_PATH} with
     * {@code ALTERNATIVE_JRE_PATH_ENABLED} set to {@code true} in an Application configuration, the
     * {@code jreName} of the Maven runner settings in a Maven one. {@code null} when it pins none — a
     * {@code jreName} that names one of IntelliJ's own JDKs ({@code #USE_PROJECT_JDK}, {@code #JAVA_HOME},
     * {@code #JAVA_INTERNAL}) pins nothing.
     */
    static String pinnedJre(byte[] onDisk) {
        String body = shownBody(onDisk);
        Matcher path = JRE_PATH.matcher(body);
        if (path.find() && JRE_ENABLED.matcher(body).find()) {
            String jre = unescapeAttribute(path.group(1));
            return jre.isBlank() ? null : jre;
        }
        Matcher name = JRE_NAME.matcher(body);
        if (!name.find()) {
            return null;
        }
        String jre = unescapeAttribute(name.group(1));
        return jre.isBlank() || jre.startsWith("#") ? null : jre;
    }

    /** Undoes {@link RunConfigurationRenderer#escapeAttribute(String)}, and {@code &apos;}. */
    private static String unescapeAttribute(String value) {
        return value.replace("&quot;", "\"").replace("&apos;", "'").replace("&lt;", "<").replace("&gt;", ">")
                .replace("&#10;", "\n").replace("&#13;", "\r").replace("&#9;", "\t").replace("&amp;", "&");
    }

    private static String normalize(String content) {
        String text = content.replace("\r\n", "\n");
        int end = text.length();
        while (end > 0 && text.charAt(end - 1) == '\n') {
            end--;
        }
        return text.substring(0, end);
    }
}
